package com.yh.tradease.sales.dao;

import com.yh.tradease.sales.entity.SaleRecord;
import com.yh.tradease.sales.entity.SaleRecordExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface SaleRecordMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sale_record
	 * @mbg.generated  Mon Dec 10 23:32:09 CST 2018
	 */
	long countByExample(SaleRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sale_record
	 * @mbg.generated  Mon Dec 10 23:32:09 CST 2018
	 */
	int deleteByExample(SaleRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sale_record
	 * @mbg.generated  Mon Dec 10 23:32:09 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sale_record
	 * @mbg.generated  Mon Dec 10 23:32:09 CST 2018
	 */
	int insert(SaleRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sale_record
	 * @mbg.generated  Mon Dec 10 23:32:09 CST 2018
	 */
	int insertSelective(SaleRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sale_record
	 * @mbg.generated  Mon Dec 10 23:32:09 CST 2018
	 */
	List<SaleRecord> selectByExample(SaleRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sale_record
	 * @mbg.generated  Mon Dec 10 23:32:09 CST 2018
	 */
	SaleRecord selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sale_record
	 * @mbg.generated  Mon Dec 10 23:32:09 CST 2018
	 */
	int updateByExampleSelective(@Param("record") SaleRecord record, @Param("example") SaleRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sale_record
	 * @mbg.generated  Mon Dec 10 23:32:09 CST 2018
	 */
	int updateByExample(@Param("record") SaleRecord record, @Param("example") SaleRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sale_record
	 * @mbg.generated  Mon Dec 10 23:32:09 CST 2018
	 */
	int updateByPrimaryKeySelective(SaleRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sale_record
	 * @mbg.generated  Mon Dec 10 23:32:09 CST 2018
	 */
	int updateByPrimaryKey(SaleRecord record);
}