package com.yh.tradease.sales.dao;

import com.yh.tradease.sales.entity.WholesaleRecord;
import com.yh.tradease.sales.entity.WholesaleRecordExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface WholesaleRecordMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wholesale_record
	 * @mbg.generated  Mon Dec 17 00:39:32 CST 2018
	 */
	long countByExample(WholesaleRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wholesale_record
	 * @mbg.generated  Mon Dec 17 00:39:32 CST 2018
	 */
	int deleteByExample(WholesaleRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wholesale_record
	 * @mbg.generated  Mon Dec 17 00:39:32 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wholesale_record
	 * @mbg.generated  Mon Dec 17 00:39:32 CST 2018
	 */
	int insert(WholesaleRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wholesale_record
	 * @mbg.generated  Mon Dec 17 00:39:32 CST 2018
	 */
	int insertSelective(WholesaleRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wholesale_record
	 * @mbg.generated  Mon Dec 17 00:39:32 CST 2018
	 */
	List<WholesaleRecord> selectByExample(WholesaleRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wholesale_record
	 * @mbg.generated  Mon Dec 17 00:39:32 CST 2018
	 */
	WholesaleRecord selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wholesale_record
	 * @mbg.generated  Mon Dec 17 00:39:32 CST 2018
	 */
	int updateByExampleSelective(@Param("record") WholesaleRecord record,
			@Param("example") WholesaleRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wholesale_record
	 * @mbg.generated  Mon Dec 17 00:39:32 CST 2018
	 */
	int updateByExample(@Param("record") WholesaleRecord record, @Param("example") WholesaleRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wholesale_record
	 * @mbg.generated  Mon Dec 17 00:39:32 CST 2018
	 */
	int updateByPrimaryKeySelective(WholesaleRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wholesale_record
	 * @mbg.generated  Mon Dec 17 00:39:32 CST 2018
	 */
	int updateByPrimaryKey(WholesaleRecord record);
}