package com.yh.tradease.stock.entity;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import org.springframework.format.annotation.DateTimeFormat;

public class InStock implements Serializable{
    /**   
	 * @Fields serialVersionUID : TODO(用一句话描述这个变量表示什么)   
	 */ 
	private static final long serialVersionUID = 1L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_stock.id
     *
     * @mbg.generated Thu Dec 20 00:21:32 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_stock.name
     *
     * @mbg.generated Thu Dec 20 00:21:32 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_stock.stock_time
     *
     * @mbg.generated Thu Dec 20 00:21:32 CST 2018
     */
	@DateTimeFormat(pattern = "yyyy-MM-dd HH:ss:mm")
    private Date stockTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_stock.transactor
     *
     * @mbg.generated Thu Dec 20 00:21:32 CST 2018
     */
    private String transactor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_stock.transactor_id
     *
     * @mbg.generated Thu Dec 20 00:21:32 CST 2018
     */
    private Integer transactorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_stock.stock_type
     *
     * @mbg.generated Thu Dec 20 00:21:32 CST 2018
     */
    private Byte stockType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_stock.in_status
     *
     * @mbg.generated Thu Dec 20 00:21:32 CST 2018
     */
    private Byte inStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_stock.delivery_type
     *
     * @mbg.generated Thu Dec 20 00:21:32 CST 2018
     */
    private Byte deliveryType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_stock.remark
     *
     * @mbg.generated Thu Dec 20 00:21:32 CST 2018
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_stock.total_price
     *
     * @mbg.generated Thu Dec 20 00:21:32 CST 2018
     */
    private Double totalPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_stock.real_price
     *
     * @mbg.generated Thu Dec 20 00:21:32 CST 2018
     */
    private Double realPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_stock.payed
     *
     * @mbg.generated Thu Dec 20 00:21:32 CST 2018
     */
    private Double payed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_stock.unpayed
     *
     * @mbg.generated Thu Dec 20 00:21:32 CST 2018
     */
    private Double unpayed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_stock.cdate
     *
     * @mbg.generated Thu Dec 20 00:21:32 CST 2018
     */
	@DateTimeFormat(pattern = "yyyy-MM-dd HH:ss:mm")
    private Date cdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_stock.mdate
     *
     * @mbg.generated Thu Dec 20 00:21:32 CST 2018
     */
	@DateTimeFormat(pattern = "yyyy-MM-dd HH:ss:mm")
    private Date mdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_stock.flag
     *
     * @mbg.generated Thu Dec 20 00:21:32 CST 2018
     */
    private Byte flag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_stock.id
     *
     * @return the value of in_stock.id
     *
     * @mbg.generated Thu Dec 20 00:21:32 CST 2018
     * 
     */
    private List<InStockDetail> inStockDetail;
    
    
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_stock.id
     *
     * @param id the value for in_stock.id
     *
     * @mbg.generated Thu Dec 20 00:21:32 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_stock.name
     *
     * @return the value of in_stock.name
     *
     * @mbg.generated Thu Dec 20 00:21:32 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_stock.name
     *
     * @param name the value for in_stock.name
     *
     * @mbg.generated Thu Dec 20 00:21:32 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_stock.stock_time
     *
     * @return the value of in_stock.stock_time
     *
     * @mbg.generated Thu Dec 20 00:21:32 CST 2018
     */
    public Date getStockTime() {
        return stockTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_stock.stock_time
     *
     * @param stockTime the value for in_stock.stock_time
     *
     * @mbg.generated Thu Dec 20 00:21:32 CST 2018
     */
    public void setStockTime(Date stockTime) {
        this.stockTime = stockTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_stock.transactor
     *
     * @return the value of in_stock.transactor
     *
     * @mbg.generated Thu Dec 20 00:21:32 CST 2018
     */
    public String getTransactor() {
        return transactor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_stock.transactor
     *
     * @param transactor the value for in_stock.transactor
     *
     * @mbg.generated Thu Dec 20 00:21:32 CST 2018
     */
    public void setTransactor(String transactor) {
        this.transactor = transactor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_stock.transactor_id
     *
     * @return the value of in_stock.transactor_id
     *
     * @mbg.generated Thu Dec 20 00:21:32 CST 2018
     */
    public Integer getTransactorId() {
        return transactorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_stock.transactor_id
     *
     * @param transactorId the value for in_stock.transactor_id
     *
     * @mbg.generated Thu Dec 20 00:21:32 CST 2018
     */
    public void setTransactorId(Integer transactorId) {
        this.transactorId = transactorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_stock.stock_type
     *
     * @return the value of in_stock.stock_type
     *
     * @mbg.generated Thu Dec 20 00:21:32 CST 2018
     */
    public Byte getStockType() {
        return stockType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_stock.stock_type
     *
     * @param stockType the value for in_stock.stock_type
     *
     * @mbg.generated Thu Dec 20 00:21:32 CST 2018
     */
    public void setStockType(Byte stockType) {
        this.stockType = stockType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_stock.in_status
     *
     * @return the value of in_stock.in_status
     *
     * @mbg.generated Thu Dec 20 00:21:32 CST 2018
     */
    public Byte getInStatus() {
        return inStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_stock.in_status
     *
     * @param inStatus the value for in_stock.in_status
     *
     * @mbg.generated Thu Dec 20 00:21:32 CST 2018
     */
    public void setInStatus(Byte inStatus) {
        this.inStatus = inStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_stock.delivery_type
     *
     * @return the value of in_stock.delivery_type
     *
     * @mbg.generated Thu Dec 20 00:21:32 CST 2018
     */
    public Byte getDeliveryType() {
        return deliveryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_stock.delivery_type
     *
     * @param deliveryType the value for in_stock.delivery_type
     *
     * @mbg.generated Thu Dec 20 00:21:32 CST 2018
     */
    public void setDeliveryType(Byte deliveryType) {
        this.deliveryType = deliveryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_stock.remark
     *
     * @return the value of in_stock.remark
     *
     * @mbg.generated Thu Dec 20 00:21:32 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_stock.remark
     *
     * @param remark the value for in_stock.remark
     *
     * @mbg.generated Thu Dec 20 00:21:32 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_stock.total_price
     *
     * @return the value of in_stock.total_price
     *
     * @mbg.generated Thu Dec 20 00:21:32 CST 2018
     */
    public Double getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_stock.total_price
     *
     * @param totalPrice the value for in_stock.total_price
     *
     * @mbg.generated Thu Dec 20 00:21:32 CST 2018
     */
    public void setTotalPrice(Double totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_stock.real_price
     *
     * @return the value of in_stock.real_price
     *
     * @mbg.generated Thu Dec 20 00:21:32 CST 2018
     */
    public Double getRealPrice() {
        return realPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_stock.real_price
     *
     * @param realPrice the value for in_stock.real_price
     *
     * @mbg.generated Thu Dec 20 00:21:32 CST 2018
     */
    public void setRealPrice(Double realPrice) {
        this.realPrice = realPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_stock.payed
     *
     * @return the value of in_stock.payed
     *
     * @mbg.generated Thu Dec 20 00:21:32 CST 2018
     */
    public Double getPayed() {
        return payed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_stock.payed
     *
     * @param payed the value for in_stock.payed
     *
     * @mbg.generated Thu Dec 20 00:21:32 CST 2018
     */
    public void setPayed(Double payed) {
        this.payed = payed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_stock.unpayed
     *
     * @return the value of in_stock.unpayed
     *
     * @mbg.generated Thu Dec 20 00:21:32 CST 2018
     */
    public Double getUnpayed() {
        return unpayed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_stock.unpayed
     *
     * @param unpayed the value for in_stock.unpayed
     *
     * @mbg.generated Thu Dec 20 00:21:32 CST 2018
     */
    public void setUnpayed(Double unpayed) {
        this.unpayed = unpayed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_stock.cdate
     *
     * @return the value of in_stock.cdate
     *
     * @mbg.generated Thu Dec 20 00:21:32 CST 2018
     */
    public Date getCdate() {
        return cdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_stock.cdate
     *
     * @param cdate the value for in_stock.cdate
     *
     * @mbg.generated Thu Dec 20 00:21:32 CST 2018
     */
    public void setCdate(Date cdate) {
        this.cdate = cdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_stock.mdate
     *
     * @return the value of in_stock.mdate
     *
     * @mbg.generated Thu Dec 20 00:21:32 CST 2018
     */
    public Date getMdate() {
        return mdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_stock.mdate
     *
     * @param mdate the value for in_stock.mdate
     *
     * @mbg.generated Thu Dec 20 00:21:32 CST 2018
     */
    public void setMdate(Date mdate) {
        this.mdate = mdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_stock.flag
     *
     * @return the value of in_stock.flag
     *
     * @mbg.generated Thu Dec 20 00:21:32 CST 2018
     */
    public Byte getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_stock.flag
     *
     * @param flag the value for in_stock.flag
     *
     * @mbg.generated Thu Dec 20 00:21:32 CST 2018
     */
    public void setFlag(Byte flag) {
        this.flag = flag;
    }

	public List<InStockDetail> getInStockDetail() {
		return inStockDetail;
	}

	public void setInStockDetail(List<InStockDetail> inStockDetail) {
		this.inStockDetail = inStockDetail;
	}
    
    
}