package com.yh.tradease.stock.entity;

import java.util.Date;

public class StorageInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column storage_info.id
	 * @mbg.generated  Sun Dec 23 22:01:32 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column storage_info.product_id
	 * @mbg.generated  Sun Dec 23 22:01:32 CST 2018
	 */
	private Integer productId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column storage_info.product_name
	 * @mbg.generated  Sun Dec 23 22:01:32 CST 2018
	 */
	private String productName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column storage_info.remark
	 * @mbg.generated  Sun Dec 23 22:01:32 CST 2018
	 */
	private String remark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column storage_info.unit_id
	 * @mbg.generated  Sun Dec 23 22:01:32 CST 2018
	 */
	private Integer unitId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column storage_info.unit_name
	 * @mbg.generated  Sun Dec 23 22:01:32 CST 2018
	 */
	private String unitName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column storage_info.storage_number
	 * @mbg.generated  Sun Dec 23 22:01:32 CST 2018
	 */
	private Double storageNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column storage_info.storage_freeze
	 * @mbg.generated  Sun Dec 23 22:01:32 CST 2018
	 */
	private Double storageFreeze;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column storage_info.storage_onway
	 * @mbg.generated  Sun Dec 23 22:01:32 CST 2018
	 */
	private Double storageOnway;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column storage_info.storage_avaliable
	 * @mbg.generated  Sun Dec 23 22:01:32 CST 2018
	 */
	private Double storageAvaliable;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column storage_info.cdate
	 * @mbg.generated  Sun Dec 23 22:01:32 CST 2018
	 */
	private Date cdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column storage_info.mdate
	 * @mbg.generated  Sun Dec 23 22:01:32 CST 2018
	 */
	private Date mdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column storage_info.min_storage
	 * @mbg.generated  Sun Dec 23 22:01:32 CST 2018
	 */
	private Double minStorage;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column storage_info.max_storage
	 * @mbg.generated  Sun Dec 23 22:01:32 CST 2018
	 */
	private Double maxStorage;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column storage_info.flag
	 * @mbg.generated  Sun Dec 23 22:01:32 CST 2018
	 */
	private Byte flag;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column storage_info.id
	 * @return  the value of storage_info.id
	 * @mbg.generated  Sun Dec 23 22:01:32 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column storage_info.id
	 * @param id  the value for storage_info.id
	 * @mbg.generated  Sun Dec 23 22:01:32 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column storage_info.product_id
	 * @return  the value of storage_info.product_id
	 * @mbg.generated  Sun Dec 23 22:01:32 CST 2018
	 */
	public Integer getProductId() {
		return productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column storage_info.product_id
	 * @param productId  the value for storage_info.product_id
	 * @mbg.generated  Sun Dec 23 22:01:32 CST 2018
	 */
	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column storage_info.product_name
	 * @return  the value of storage_info.product_name
	 * @mbg.generated  Sun Dec 23 22:01:32 CST 2018
	 */
	public String getProductName() {
		return productName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column storage_info.product_name
	 * @param productName  the value for storage_info.product_name
	 * @mbg.generated  Sun Dec 23 22:01:32 CST 2018
	 */
	public void setProductName(String productName) {
		this.productName = productName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column storage_info.remark
	 * @return  the value of storage_info.remark
	 * @mbg.generated  Sun Dec 23 22:01:32 CST 2018
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column storage_info.remark
	 * @param remark  the value for storage_info.remark
	 * @mbg.generated  Sun Dec 23 22:01:32 CST 2018
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column storage_info.unit_id
	 * @return  the value of storage_info.unit_id
	 * @mbg.generated  Sun Dec 23 22:01:32 CST 2018
	 */
	public Integer getUnitId() {
		return unitId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column storage_info.unit_id
	 * @param unitId  the value for storage_info.unit_id
	 * @mbg.generated  Sun Dec 23 22:01:32 CST 2018
	 */
	public void setUnitId(Integer unitId) {
		this.unitId = unitId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column storage_info.unit_name
	 * @return  the value of storage_info.unit_name
	 * @mbg.generated  Sun Dec 23 22:01:32 CST 2018
	 */
	public String getUnitName() {
		return unitName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column storage_info.unit_name
	 * @param unitName  the value for storage_info.unit_name
	 * @mbg.generated  Sun Dec 23 22:01:32 CST 2018
	 */
	public void setUnitName(String unitName) {
		this.unitName = unitName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column storage_info.storage_number
	 * @return  the value of storage_info.storage_number
	 * @mbg.generated  Sun Dec 23 22:01:32 CST 2018
	 */
	public Double getStorageNumber() {
		return storageNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column storage_info.storage_number
	 * @param storageNumber  the value for storage_info.storage_number
	 * @mbg.generated  Sun Dec 23 22:01:32 CST 2018
	 */
	public void setStorageNumber(Double storageNumber) {
		this.storageNumber = storageNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column storage_info.storage_freeze
	 * @return  the value of storage_info.storage_freeze
	 * @mbg.generated  Sun Dec 23 22:01:32 CST 2018
	 */
	public Double getStorageFreeze() {
		return storageFreeze;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column storage_info.storage_freeze
	 * @param storageFreeze  the value for storage_info.storage_freeze
	 * @mbg.generated  Sun Dec 23 22:01:32 CST 2018
	 */
	public void setStorageFreeze(Double storageFreeze) {
		this.storageFreeze = storageFreeze;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column storage_info.storage_onway
	 * @return  the value of storage_info.storage_onway
	 * @mbg.generated  Sun Dec 23 22:01:32 CST 2018
	 */
	public Double getStorageOnway() {
		return storageOnway;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column storage_info.storage_onway
	 * @param storageOnway  the value for storage_info.storage_onway
	 * @mbg.generated  Sun Dec 23 22:01:32 CST 2018
	 */
	public void setStorageOnway(Double storageOnway) {
		this.storageOnway = storageOnway;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column storage_info.storage_avaliable
	 * @return  the value of storage_info.storage_avaliable
	 * @mbg.generated  Sun Dec 23 22:01:32 CST 2018
	 */
	public Double getStorageAvaliable() {
		return storageAvaliable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column storage_info.storage_avaliable
	 * @param storageAvaliable  the value for storage_info.storage_avaliable
	 * @mbg.generated  Sun Dec 23 22:01:32 CST 2018
	 */
	public void setStorageAvaliable(Double storageAvaliable) {
		this.storageAvaliable = storageAvaliable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column storage_info.cdate
	 * @return  the value of storage_info.cdate
	 * @mbg.generated  Sun Dec 23 22:01:32 CST 2018
	 */
	public Date getCdate() {
		return cdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column storage_info.cdate
	 * @param cdate  the value for storage_info.cdate
	 * @mbg.generated  Sun Dec 23 22:01:32 CST 2018
	 */
	public void setCdate(Date cdate) {
		this.cdate = cdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column storage_info.mdate
	 * @return  the value of storage_info.mdate
	 * @mbg.generated  Sun Dec 23 22:01:32 CST 2018
	 */
	public Date getMdate() {
		return mdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column storage_info.mdate
	 * @param mdate  the value for storage_info.mdate
	 * @mbg.generated  Sun Dec 23 22:01:32 CST 2018
	 */
	public void setMdate(Date mdate) {
		this.mdate = mdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column storage_info.min_storage
	 * @return  the value of storage_info.min_storage
	 * @mbg.generated  Sun Dec 23 22:01:32 CST 2018
	 */
	public Double getMinStorage() {
		return minStorage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column storage_info.min_storage
	 * @param minStorage  the value for storage_info.min_storage
	 * @mbg.generated  Sun Dec 23 22:01:32 CST 2018
	 */
	public void setMinStorage(Double minStorage) {
		this.minStorage = minStorage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column storage_info.max_storage
	 * @return  the value of storage_info.max_storage
	 * @mbg.generated  Sun Dec 23 22:01:32 CST 2018
	 */
	public Double getMaxStorage() {
		return maxStorage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column storage_info.max_storage
	 * @param maxStorage  the value for storage_info.max_storage
	 * @mbg.generated  Sun Dec 23 22:01:32 CST 2018
	 */
	public void setMaxStorage(Double maxStorage) {
		this.maxStorage = maxStorage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column storage_info.flag
	 * @return  the value of storage_info.flag
	 * @mbg.generated  Sun Dec 23 22:01:32 CST 2018
	 */
	public Byte getFlag() {
		return flag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column storage_info.flag
	 * @param flag  the value for storage_info.flag
	 * @mbg.generated  Sun Dec 23 22:01:32 CST 2018
	 */
	public void setFlag(Byte flag) {
		this.flag = flag;
	}
}