package com.yh.tradease.serve.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ProductInstallExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table product_install
	 * @mbg.generated  Mon Dec 17 01:45:08 CST 2018
	 */
	protected String orderByClause;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table product_install
	 * @mbg.generated  Mon Dec 17 01:45:08 CST 2018
	 */
	protected boolean distinct;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table product_install
	 * @mbg.generated  Mon Dec 17 01:45:08 CST 2018
	 */
	protected List<Criteria> oredCriteria;

	private Integer limit;

	private Integer offset;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_install
	 * @mbg.generated  Mon Dec 17 01:45:08 CST 2018
	 */
	public ProductInstallExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_install
	 * @mbg.generated  Mon Dec 17 01:45:08 CST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_install
	 * @mbg.generated  Mon Dec 17 01:45:08 CST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_install
	 * @mbg.generated  Mon Dec 17 01:45:08 CST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_install
	 * @mbg.generated  Mon Dec 17 01:45:08 CST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_install
	 * @mbg.generated  Mon Dec 17 01:45:08 CST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_install
	 * @mbg.generated  Mon Dec 17 01:45:08 CST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_install
	 * @mbg.generated  Mon Dec 17 01:45:08 CST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_install
	 * @mbg.generated  Mon Dec 17 01:45:08 CST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_install
	 * @mbg.generated  Mon Dec 17 01:45:08 CST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_install
	 * @mbg.generated  Mon Dec 17 01:45:08 CST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	public void setLimit(Integer limit) {
		this.limit = limit;
	}

	public Integer getLimit() {
		return limit;
	}

	public void setOffset(Integer offset) {
		this.offset = offset;
	}

	public Integer getOffset() {
		return offset;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table product_install
	 * @mbg.generated  Mon Dec 17 01:45:08 CST 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andOrderIdIsNull() {
			addCriterion("order_id is null");
			return (Criteria) this;
		}

		public Criteria andOrderIdIsNotNull() {
			addCriterion("order_id is not null");
			return (Criteria) this;
		}

		public Criteria andOrderIdEqualTo(Integer value) {
			addCriterion("order_id =", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdNotEqualTo(Integer value) {
			addCriterion("order_id <>", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdGreaterThan(Integer value) {
			addCriterion("order_id >", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("order_id >=", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdLessThan(Integer value) {
			addCriterion("order_id <", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdLessThanOrEqualTo(Integer value) {
			addCriterion("order_id <=", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdIn(List<Integer> values) {
			addCriterion("order_id in", values, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdNotIn(List<Integer> values) {
			addCriterion("order_id not in", values, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdBetween(Integer value1, Integer value2) {
			addCriterion("order_id between", value1, value2, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdNotBetween(Integer value1, Integer value2) {
			addCriterion("order_id not between", value1, value2, "orderId");
			return (Criteria) this;
		}

		public Criteria andProductIdIsNull() {
			addCriterion("product_id is null");
			return (Criteria) this;
		}

		public Criteria andProductIdIsNotNull() {
			addCriterion("product_id is not null");
			return (Criteria) this;
		}

		public Criteria andProductIdEqualTo(Integer value) {
			addCriterion("product_id =", value, "productId");
			return (Criteria) this;
		}

		public Criteria andProductIdNotEqualTo(Integer value) {
			addCriterion("product_id <>", value, "productId");
			return (Criteria) this;
		}

		public Criteria andProductIdGreaterThan(Integer value) {
			addCriterion("product_id >", value, "productId");
			return (Criteria) this;
		}

		public Criteria andProductIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("product_id >=", value, "productId");
			return (Criteria) this;
		}

		public Criteria andProductIdLessThan(Integer value) {
			addCriterion("product_id <", value, "productId");
			return (Criteria) this;
		}

		public Criteria andProductIdLessThanOrEqualTo(Integer value) {
			addCriterion("product_id <=", value, "productId");
			return (Criteria) this;
		}

		public Criteria andProductIdIn(List<Integer> values) {
			addCriterion("product_id in", values, "productId");
			return (Criteria) this;
		}

		public Criteria andProductIdNotIn(List<Integer> values) {
			addCriterion("product_id not in", values, "productId");
			return (Criteria) this;
		}

		public Criteria andProductIdBetween(Integer value1, Integer value2) {
			addCriterion("product_id between", value1, value2, "productId");
			return (Criteria) this;
		}

		public Criteria andProductIdNotBetween(Integer value1, Integer value2) {
			addCriterion("product_id not between", value1, value2, "productId");
			return (Criteria) this;
		}

		public Criteria andProductNameIsNull() {
			addCriterion("product_name is null");
			return (Criteria) this;
		}

		public Criteria andProductNameIsNotNull() {
			addCriterion("product_name is not null");
			return (Criteria) this;
		}

		public Criteria andProductNameEqualTo(String value) {
			addCriterion("product_name =", value, "productName");
			return (Criteria) this;
		}

		public Criteria andProductNameNotEqualTo(String value) {
			addCriterion("product_name <>", value, "productName");
			return (Criteria) this;
		}

		public Criteria andProductNameGreaterThan(String value) {
			addCriterion("product_name >", value, "productName");
			return (Criteria) this;
		}

		public Criteria andProductNameGreaterThanOrEqualTo(String value) {
			addCriterion("product_name >=", value, "productName");
			return (Criteria) this;
		}

		public Criteria andProductNameLessThan(String value) {
			addCriterion("product_name <", value, "productName");
			return (Criteria) this;
		}

		public Criteria andProductNameLessThanOrEqualTo(String value) {
			addCriterion("product_name <=", value, "productName");
			return (Criteria) this;
		}

		public Criteria andProductNameLike(String value) {
			addCriterion("product_name like", value, "productName");
			return (Criteria) this;
		}

		public Criteria andProductNameNotLike(String value) {
			addCriterion("product_name not like", value, "productName");
			return (Criteria) this;
		}

		public Criteria andProductNameIn(List<String> values) {
			addCriterion("product_name in", values, "productName");
			return (Criteria) this;
		}

		public Criteria andProductNameNotIn(List<String> values) {
			addCriterion("product_name not in", values, "productName");
			return (Criteria) this;
		}

		public Criteria andProductNameBetween(String value1, String value2) {
			addCriterion("product_name between", value1, value2, "productName");
			return (Criteria) this;
		}

		public Criteria andProductNameNotBetween(String value1, String value2) {
			addCriterion("product_name not between", value1, value2, "productName");
			return (Criteria) this;
		}

		public Criteria andInnerCodeIsNull() {
			addCriterion("inner_code is null");
			return (Criteria) this;
		}

		public Criteria andInnerCodeIsNotNull() {
			addCriterion("inner_code is not null");
			return (Criteria) this;
		}

		public Criteria andInnerCodeEqualTo(String value) {
			addCriterion("inner_code =", value, "innerCode");
			return (Criteria) this;
		}

		public Criteria andInnerCodeNotEqualTo(String value) {
			addCriterion("inner_code <>", value, "innerCode");
			return (Criteria) this;
		}

		public Criteria andInnerCodeGreaterThan(String value) {
			addCriterion("inner_code >", value, "innerCode");
			return (Criteria) this;
		}

		public Criteria andInnerCodeGreaterThanOrEqualTo(String value) {
			addCriterion("inner_code >=", value, "innerCode");
			return (Criteria) this;
		}

		public Criteria andInnerCodeLessThan(String value) {
			addCriterion("inner_code <", value, "innerCode");
			return (Criteria) this;
		}

		public Criteria andInnerCodeLessThanOrEqualTo(String value) {
			addCriterion("inner_code <=", value, "innerCode");
			return (Criteria) this;
		}

		public Criteria andInnerCodeLike(String value) {
			addCriterion("inner_code like", value, "innerCode");
			return (Criteria) this;
		}

		public Criteria andInnerCodeNotLike(String value) {
			addCriterion("inner_code not like", value, "innerCode");
			return (Criteria) this;
		}

		public Criteria andInnerCodeIn(List<String> values) {
			addCriterion("inner_code in", values, "innerCode");
			return (Criteria) this;
		}

		public Criteria andInnerCodeNotIn(List<String> values) {
			addCriterion("inner_code not in", values, "innerCode");
			return (Criteria) this;
		}

		public Criteria andInnerCodeBetween(String value1, String value2) {
			addCriterion("inner_code between", value1, value2, "innerCode");
			return (Criteria) this;
		}

		public Criteria andInnerCodeNotBetween(String value1, String value2) {
			addCriterion("inner_code not between", value1, value2, "innerCode");
			return (Criteria) this;
		}

		public Criteria andOutterCodeIsNull() {
			addCriterion("outter_code is null");
			return (Criteria) this;
		}

		public Criteria andOutterCodeIsNotNull() {
			addCriterion("outter_code is not null");
			return (Criteria) this;
		}

		public Criteria andOutterCodeEqualTo(String value) {
			addCriterion("outter_code =", value, "outterCode");
			return (Criteria) this;
		}

		public Criteria andOutterCodeNotEqualTo(String value) {
			addCriterion("outter_code <>", value, "outterCode");
			return (Criteria) this;
		}

		public Criteria andOutterCodeGreaterThan(String value) {
			addCriterion("outter_code >", value, "outterCode");
			return (Criteria) this;
		}

		public Criteria andOutterCodeGreaterThanOrEqualTo(String value) {
			addCriterion("outter_code >=", value, "outterCode");
			return (Criteria) this;
		}

		public Criteria andOutterCodeLessThan(String value) {
			addCriterion("outter_code <", value, "outterCode");
			return (Criteria) this;
		}

		public Criteria andOutterCodeLessThanOrEqualTo(String value) {
			addCriterion("outter_code <=", value, "outterCode");
			return (Criteria) this;
		}

		public Criteria andOutterCodeLike(String value) {
			addCriterion("outter_code like", value, "outterCode");
			return (Criteria) this;
		}

		public Criteria andOutterCodeNotLike(String value) {
			addCriterion("outter_code not like", value, "outterCode");
			return (Criteria) this;
		}

		public Criteria andOutterCodeIn(List<String> values) {
			addCriterion("outter_code in", values, "outterCode");
			return (Criteria) this;
		}

		public Criteria andOutterCodeNotIn(List<String> values) {
			addCriterion("outter_code not in", values, "outterCode");
			return (Criteria) this;
		}

		public Criteria andOutterCodeBetween(String value1, String value2) {
			addCriterion("outter_code between", value1, value2, "outterCode");
			return (Criteria) this;
		}

		public Criteria andOutterCodeNotBetween(String value1, String value2) {
			addCriterion("outter_code not between", value1, value2, "outterCode");
			return (Criteria) this;
		}

		public Criteria andMaterialOneIsNull() {
			addCriterion("material_one is null");
			return (Criteria) this;
		}

		public Criteria andMaterialOneIsNotNull() {
			addCriterion("material_one is not null");
			return (Criteria) this;
		}

		public Criteria andMaterialOneEqualTo(Double value) {
			addCriterion("material_one =", value, "materialOne");
			return (Criteria) this;
		}

		public Criteria andMaterialOneNotEqualTo(Double value) {
			addCriterion("material_one <>", value, "materialOne");
			return (Criteria) this;
		}

		public Criteria andMaterialOneGreaterThan(Double value) {
			addCriterion("material_one >", value, "materialOne");
			return (Criteria) this;
		}

		public Criteria andMaterialOneGreaterThanOrEqualTo(Double value) {
			addCriterion("material_one >=", value, "materialOne");
			return (Criteria) this;
		}

		public Criteria andMaterialOneLessThan(Double value) {
			addCriterion("material_one <", value, "materialOne");
			return (Criteria) this;
		}

		public Criteria andMaterialOneLessThanOrEqualTo(Double value) {
			addCriterion("material_one <=", value, "materialOne");
			return (Criteria) this;
		}

		public Criteria andMaterialOneIn(List<Double> values) {
			addCriterion("material_one in", values, "materialOne");
			return (Criteria) this;
		}

		public Criteria andMaterialOneNotIn(List<Double> values) {
			addCriterion("material_one not in", values, "materialOne");
			return (Criteria) this;
		}

		public Criteria andMaterialOneBetween(Double value1, Double value2) {
			addCriterion("material_one between", value1, value2, "materialOne");
			return (Criteria) this;
		}

		public Criteria andMaterialOneNotBetween(Double value1, Double value2) {
			addCriterion("material_one not between", value1, value2, "materialOne");
			return (Criteria) this;
		}

		public Criteria andMaterialTwoIsNull() {
			addCriterion("material_two is null");
			return (Criteria) this;
		}

		public Criteria andMaterialTwoIsNotNull() {
			addCriterion("material_two is not null");
			return (Criteria) this;
		}

		public Criteria andMaterialTwoEqualTo(Double value) {
			addCriterion("material_two =", value, "materialTwo");
			return (Criteria) this;
		}

		public Criteria andMaterialTwoNotEqualTo(Double value) {
			addCriterion("material_two <>", value, "materialTwo");
			return (Criteria) this;
		}

		public Criteria andMaterialTwoGreaterThan(Double value) {
			addCriterion("material_two >", value, "materialTwo");
			return (Criteria) this;
		}

		public Criteria andMaterialTwoGreaterThanOrEqualTo(Double value) {
			addCriterion("material_two >=", value, "materialTwo");
			return (Criteria) this;
		}

		public Criteria andMaterialTwoLessThan(Double value) {
			addCriterion("material_two <", value, "materialTwo");
			return (Criteria) this;
		}

		public Criteria andMaterialTwoLessThanOrEqualTo(Double value) {
			addCriterion("material_two <=", value, "materialTwo");
			return (Criteria) this;
		}

		public Criteria andMaterialTwoIn(List<Double> values) {
			addCriterion("material_two in", values, "materialTwo");
			return (Criteria) this;
		}

		public Criteria andMaterialTwoNotIn(List<Double> values) {
			addCriterion("material_two not in", values, "materialTwo");
			return (Criteria) this;
		}

		public Criteria andMaterialTwoBetween(Double value1, Double value2) {
			addCriterion("material_two between", value1, value2, "materialTwo");
			return (Criteria) this;
		}

		public Criteria andMaterialTwoNotBetween(Double value1, Double value2) {
			addCriterion("material_two not between", value1, value2, "materialTwo");
			return (Criteria) this;
		}

		public Criteria andMaterialThreeIsNull() {
			addCriterion("material_three is null");
			return (Criteria) this;
		}

		public Criteria andMaterialThreeIsNotNull() {
			addCriterion("material_three is not null");
			return (Criteria) this;
		}

		public Criteria andMaterialThreeEqualTo(Double value) {
			addCriterion("material_three =", value, "materialThree");
			return (Criteria) this;
		}

		public Criteria andMaterialThreeNotEqualTo(Double value) {
			addCriterion("material_three <>", value, "materialThree");
			return (Criteria) this;
		}

		public Criteria andMaterialThreeGreaterThan(Double value) {
			addCriterion("material_three >", value, "materialThree");
			return (Criteria) this;
		}

		public Criteria andMaterialThreeGreaterThanOrEqualTo(Double value) {
			addCriterion("material_three >=", value, "materialThree");
			return (Criteria) this;
		}

		public Criteria andMaterialThreeLessThan(Double value) {
			addCriterion("material_three <", value, "materialThree");
			return (Criteria) this;
		}

		public Criteria andMaterialThreeLessThanOrEqualTo(Double value) {
			addCriterion("material_three <=", value, "materialThree");
			return (Criteria) this;
		}

		public Criteria andMaterialThreeIn(List<Double> values) {
			addCriterion("material_three in", values, "materialThree");
			return (Criteria) this;
		}

		public Criteria andMaterialThreeNotIn(List<Double> values) {
			addCriterion("material_three not in", values, "materialThree");
			return (Criteria) this;
		}

		public Criteria andMaterialThreeBetween(Double value1, Double value2) {
			addCriterion("material_three between", value1, value2, "materialThree");
			return (Criteria) this;
		}

		public Criteria andMaterialThreeNotBetween(Double value1, Double value2) {
			addCriterion("material_three not between", value1, value2, "materialThree");
			return (Criteria) this;
		}

		public Criteria andMaterialFeeIsNull() {
			addCriterion("material_fee is null");
			return (Criteria) this;
		}

		public Criteria andMaterialFeeIsNotNull() {
			addCriterion("material_fee is not null");
			return (Criteria) this;
		}

		public Criteria andMaterialFeeEqualTo(Double value) {
			addCriterion("material_fee =", value, "materialFee");
			return (Criteria) this;
		}

		public Criteria andMaterialFeeNotEqualTo(Double value) {
			addCriterion("material_fee <>", value, "materialFee");
			return (Criteria) this;
		}

		public Criteria andMaterialFeeGreaterThan(Double value) {
			addCriterion("material_fee >", value, "materialFee");
			return (Criteria) this;
		}

		public Criteria andMaterialFeeGreaterThanOrEqualTo(Double value) {
			addCriterion("material_fee >=", value, "materialFee");
			return (Criteria) this;
		}

		public Criteria andMaterialFeeLessThan(Double value) {
			addCriterion("material_fee <", value, "materialFee");
			return (Criteria) this;
		}

		public Criteria andMaterialFeeLessThanOrEqualTo(Double value) {
			addCriterion("material_fee <=", value, "materialFee");
			return (Criteria) this;
		}

		public Criteria andMaterialFeeIn(List<Double> values) {
			addCriterion("material_fee in", values, "materialFee");
			return (Criteria) this;
		}

		public Criteria andMaterialFeeNotIn(List<Double> values) {
			addCriterion("material_fee not in", values, "materialFee");
			return (Criteria) this;
		}

		public Criteria andMaterialFeeBetween(Double value1, Double value2) {
			addCriterion("material_fee between", value1, value2, "materialFee");
			return (Criteria) this;
		}

		public Criteria andMaterialFeeNotBetween(Double value1, Double value2) {
			addCriterion("material_fee not between", value1, value2, "materialFee");
			return (Criteria) this;
		}

		public Criteria andServiceFeeIsNull() {
			addCriterion("service_fee is null");
			return (Criteria) this;
		}

		public Criteria andServiceFeeIsNotNull() {
			addCriterion("service_fee is not null");
			return (Criteria) this;
		}

		public Criteria andServiceFeeEqualTo(Double value) {
			addCriterion("service_fee =", value, "serviceFee");
			return (Criteria) this;
		}

		public Criteria andServiceFeeNotEqualTo(Double value) {
			addCriterion("service_fee <>", value, "serviceFee");
			return (Criteria) this;
		}

		public Criteria andServiceFeeGreaterThan(Double value) {
			addCriterion("service_fee >", value, "serviceFee");
			return (Criteria) this;
		}

		public Criteria andServiceFeeGreaterThanOrEqualTo(Double value) {
			addCriterion("service_fee >=", value, "serviceFee");
			return (Criteria) this;
		}

		public Criteria andServiceFeeLessThan(Double value) {
			addCriterion("service_fee <", value, "serviceFee");
			return (Criteria) this;
		}

		public Criteria andServiceFeeLessThanOrEqualTo(Double value) {
			addCriterion("service_fee <=", value, "serviceFee");
			return (Criteria) this;
		}

		public Criteria andServiceFeeIn(List<Double> values) {
			addCriterion("service_fee in", values, "serviceFee");
			return (Criteria) this;
		}

		public Criteria andServiceFeeNotIn(List<Double> values) {
			addCriterion("service_fee not in", values, "serviceFee");
			return (Criteria) this;
		}

		public Criteria andServiceFeeBetween(Double value1, Double value2) {
			addCriterion("service_fee between", value1, value2, "serviceFee");
			return (Criteria) this;
		}

		public Criteria andServiceFeeNotBetween(Double value1, Double value2) {
			addCriterion("service_fee not between", value1, value2, "serviceFee");
			return (Criteria) this;
		}

		public Criteria andServicesIsNull() {
			addCriterion("services is null");
			return (Criteria) this;
		}

		public Criteria andServicesIsNotNull() {
			addCriterion("services is not null");
			return (Criteria) this;
		}

		public Criteria andServicesEqualTo(String value) {
			addCriterion("services =", value, "services");
			return (Criteria) this;
		}

		public Criteria andServicesNotEqualTo(String value) {
			addCriterion("services <>", value, "services");
			return (Criteria) this;
		}

		public Criteria andServicesGreaterThan(String value) {
			addCriterion("services >", value, "services");
			return (Criteria) this;
		}

		public Criteria andServicesGreaterThanOrEqualTo(String value) {
			addCriterion("services >=", value, "services");
			return (Criteria) this;
		}

		public Criteria andServicesLessThan(String value) {
			addCriterion("services <", value, "services");
			return (Criteria) this;
		}

		public Criteria andServicesLessThanOrEqualTo(String value) {
			addCriterion("services <=", value, "services");
			return (Criteria) this;
		}

		public Criteria andServicesLike(String value) {
			addCriterion("services like", value, "services");
			return (Criteria) this;
		}

		public Criteria andServicesNotLike(String value) {
			addCriterion("services not like", value, "services");
			return (Criteria) this;
		}

		public Criteria andServicesIn(List<String> values) {
			addCriterion("services in", values, "services");
			return (Criteria) this;
		}

		public Criteria andServicesNotIn(List<String> values) {
			addCriterion("services not in", values, "services");
			return (Criteria) this;
		}

		public Criteria andServicesBetween(String value1, String value2) {
			addCriterion("services between", value1, value2, "services");
			return (Criteria) this;
		}

		public Criteria andServicesNotBetween(String value1, String value2) {
			addCriterion("services not between", value1, value2, "services");
			return (Criteria) this;
		}

		public Criteria andServiceStatusIsNull() {
			addCriterion("service_status is null");
			return (Criteria) this;
		}

		public Criteria andServiceStatusIsNotNull() {
			addCriterion("service_status is not null");
			return (Criteria) this;
		}

		public Criteria andServiceStatusEqualTo(Byte value) {
			addCriterion("service_status =", value, "serviceStatus");
			return (Criteria) this;
		}

		public Criteria andServiceStatusNotEqualTo(Byte value) {
			addCriterion("service_status <>", value, "serviceStatus");
			return (Criteria) this;
		}

		public Criteria andServiceStatusGreaterThan(Byte value) {
			addCriterion("service_status >", value, "serviceStatus");
			return (Criteria) this;
		}

		public Criteria andServiceStatusGreaterThanOrEqualTo(Byte value) {
			addCriterion("service_status >=", value, "serviceStatus");
			return (Criteria) this;
		}

		public Criteria andServiceStatusLessThan(Byte value) {
			addCriterion("service_status <", value, "serviceStatus");
			return (Criteria) this;
		}

		public Criteria andServiceStatusLessThanOrEqualTo(Byte value) {
			addCriterion("service_status <=", value, "serviceStatus");
			return (Criteria) this;
		}

		public Criteria andServiceStatusIn(List<Byte> values) {
			addCriterion("service_status in", values, "serviceStatus");
			return (Criteria) this;
		}

		public Criteria andServiceStatusNotIn(List<Byte> values) {
			addCriterion("service_status not in", values, "serviceStatus");
			return (Criteria) this;
		}

		public Criteria andServiceStatusBetween(Byte value1, Byte value2) {
			addCriterion("service_status between", value1, value2, "serviceStatus");
			return (Criteria) this;
		}

		public Criteria andServiceStatusNotBetween(Byte value1, Byte value2) {
			addCriterion("service_status not between", value1, value2, "serviceStatus");
			return (Criteria) this;
		}

		public Criteria andManIdIsNull() {
			addCriterion("man_id is null");
			return (Criteria) this;
		}

		public Criteria andManIdIsNotNull() {
			addCriterion("man_id is not null");
			return (Criteria) this;
		}

		public Criteria andManIdEqualTo(Integer value) {
			addCriterion("man_id =", value, "manId");
			return (Criteria) this;
		}

		public Criteria andManIdNotEqualTo(Integer value) {
			addCriterion("man_id <>", value, "manId");
			return (Criteria) this;
		}

		public Criteria andManIdGreaterThan(Integer value) {
			addCriterion("man_id >", value, "manId");
			return (Criteria) this;
		}

		public Criteria andManIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("man_id >=", value, "manId");
			return (Criteria) this;
		}

		public Criteria andManIdLessThan(Integer value) {
			addCriterion("man_id <", value, "manId");
			return (Criteria) this;
		}

		public Criteria andManIdLessThanOrEqualTo(Integer value) {
			addCriterion("man_id <=", value, "manId");
			return (Criteria) this;
		}

		public Criteria andManIdIn(List<Integer> values) {
			addCriterion("man_id in", values, "manId");
			return (Criteria) this;
		}

		public Criteria andManIdNotIn(List<Integer> values) {
			addCriterion("man_id not in", values, "manId");
			return (Criteria) this;
		}

		public Criteria andManIdBetween(Integer value1, Integer value2) {
			addCriterion("man_id between", value1, value2, "manId");
			return (Criteria) this;
		}

		public Criteria andManIdNotBetween(Integer value1, Integer value2) {
			addCriterion("man_id not between", value1, value2, "manId");
			return (Criteria) this;
		}

		public Criteria andServiceManIsNull() {
			addCriterion("service_man is null");
			return (Criteria) this;
		}

		public Criteria andServiceManIsNotNull() {
			addCriterion("service_man is not null");
			return (Criteria) this;
		}

		public Criteria andServiceManEqualTo(String value) {
			addCriterion("service_man =", value, "serviceMan");
			return (Criteria) this;
		}

		public Criteria andServiceManNotEqualTo(String value) {
			addCriterion("service_man <>", value, "serviceMan");
			return (Criteria) this;
		}

		public Criteria andServiceManGreaterThan(String value) {
			addCriterion("service_man >", value, "serviceMan");
			return (Criteria) this;
		}

		public Criteria andServiceManGreaterThanOrEqualTo(String value) {
			addCriterion("service_man >=", value, "serviceMan");
			return (Criteria) this;
		}

		public Criteria andServiceManLessThan(String value) {
			addCriterion("service_man <", value, "serviceMan");
			return (Criteria) this;
		}

		public Criteria andServiceManLessThanOrEqualTo(String value) {
			addCriterion("service_man <=", value, "serviceMan");
			return (Criteria) this;
		}

		public Criteria andServiceManLike(String value) {
			addCriterion("service_man like", value, "serviceMan");
			return (Criteria) this;
		}

		public Criteria andServiceManNotLike(String value) {
			addCriterion("service_man not like", value, "serviceMan");
			return (Criteria) this;
		}

		public Criteria andServiceManIn(List<String> values) {
			addCriterion("service_man in", values, "serviceMan");
			return (Criteria) this;
		}

		public Criteria andServiceManNotIn(List<String> values) {
			addCriterion("service_man not in", values, "serviceMan");
			return (Criteria) this;
		}

		public Criteria andServiceManBetween(String value1, String value2) {
			addCriterion("service_man between", value1, value2, "serviceMan");
			return (Criteria) this;
		}

		public Criteria andServiceManNotBetween(String value1, String value2) {
			addCriterion("service_man not between", value1, value2, "serviceMan");
			return (Criteria) this;
		}

		public Criteria andReceiverIsNull() {
			addCriterion("receiver is null");
			return (Criteria) this;
		}

		public Criteria andReceiverIsNotNull() {
			addCriterion("receiver is not null");
			return (Criteria) this;
		}

		public Criteria andReceiverEqualTo(String value) {
			addCriterion("receiver =", value, "receiver");
			return (Criteria) this;
		}

		public Criteria andReceiverNotEqualTo(String value) {
			addCriterion("receiver <>", value, "receiver");
			return (Criteria) this;
		}

		public Criteria andReceiverGreaterThan(String value) {
			addCriterion("receiver >", value, "receiver");
			return (Criteria) this;
		}

		public Criteria andReceiverGreaterThanOrEqualTo(String value) {
			addCriterion("receiver >=", value, "receiver");
			return (Criteria) this;
		}

		public Criteria andReceiverLessThan(String value) {
			addCriterion("receiver <", value, "receiver");
			return (Criteria) this;
		}

		public Criteria andReceiverLessThanOrEqualTo(String value) {
			addCriterion("receiver <=", value, "receiver");
			return (Criteria) this;
		}

		public Criteria andReceiverLike(String value) {
			addCriterion("receiver like", value, "receiver");
			return (Criteria) this;
		}

		public Criteria andReceiverNotLike(String value) {
			addCriterion("receiver not like", value, "receiver");
			return (Criteria) this;
		}

		public Criteria andReceiverIn(List<String> values) {
			addCriterion("receiver in", values, "receiver");
			return (Criteria) this;
		}

		public Criteria andReceiverNotIn(List<String> values) {
			addCriterion("receiver not in", values, "receiver");
			return (Criteria) this;
		}

		public Criteria andReceiverBetween(String value1, String value2) {
			addCriterion("receiver between", value1, value2, "receiver");
			return (Criteria) this;
		}

		public Criteria andReceiverNotBetween(String value1, String value2) {
			addCriterion("receiver not between", value1, value2, "receiver");
			return (Criteria) this;
		}

		public Criteria andPhoneIsNull() {
			addCriterion("phone is null");
			return (Criteria) this;
		}

		public Criteria andPhoneIsNotNull() {
			addCriterion("phone is not null");
			return (Criteria) this;
		}

		public Criteria andPhoneEqualTo(String value) {
			addCriterion("phone =", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneNotEqualTo(String value) {
			addCriterion("phone <>", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneGreaterThan(String value) {
			addCriterion("phone >", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneGreaterThanOrEqualTo(String value) {
			addCriterion("phone >=", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneLessThan(String value) {
			addCriterion("phone <", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneLessThanOrEqualTo(String value) {
			addCriterion("phone <=", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneLike(String value) {
			addCriterion("phone like", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneNotLike(String value) {
			addCriterion("phone not like", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneIn(List<String> values) {
			addCriterion("phone in", values, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneNotIn(List<String> values) {
			addCriterion("phone not in", values, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneBetween(String value1, String value2) {
			addCriterion("phone between", value1, value2, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneNotBetween(String value1, String value2) {
			addCriterion("phone not between", value1, value2, "phone");
			return (Criteria) this;
		}

		public Criteria andAddressIsNull() {
			addCriterion("address is null");
			return (Criteria) this;
		}

		public Criteria andAddressIsNotNull() {
			addCriterion("address is not null");
			return (Criteria) this;
		}

		public Criteria andAddressEqualTo(String value) {
			addCriterion("address =", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotEqualTo(String value) {
			addCriterion("address <>", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressGreaterThan(String value) {
			addCriterion("address >", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressGreaterThanOrEqualTo(String value) {
			addCriterion("address >=", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLessThan(String value) {
			addCriterion("address <", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLessThanOrEqualTo(String value) {
			addCriterion("address <=", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLike(String value) {
			addCriterion("address like", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotLike(String value) {
			addCriterion("address not like", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressIn(List<String> values) {
			addCriterion("address in", values, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotIn(List<String> values) {
			addCriterion("address not in", values, "address");
			return (Criteria) this;
		}

		public Criteria andAddressBetween(String value1, String value2) {
			addCriterion("address between", value1, value2, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotBetween(String value1, String value2) {
			addCriterion("address not between", value1, value2, "address");
			return (Criteria) this;
		}

		public Criteria andInstallTimeIsNull() {
			addCriterion("install_time is null");
			return (Criteria) this;
		}

		public Criteria andInstallTimeIsNotNull() {
			addCriterion("install_time is not null");
			return (Criteria) this;
		}

		public Criteria andInstallTimeEqualTo(Date value) {
			addCriterion("install_time =", value, "installTime");
			return (Criteria) this;
		}

		public Criteria andInstallTimeNotEqualTo(Date value) {
			addCriterion("install_time <>", value, "installTime");
			return (Criteria) this;
		}

		public Criteria andInstallTimeGreaterThan(Date value) {
			addCriterion("install_time >", value, "installTime");
			return (Criteria) this;
		}

		public Criteria andInstallTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("install_time >=", value, "installTime");
			return (Criteria) this;
		}

		public Criteria andInstallTimeLessThan(Date value) {
			addCriterion("install_time <", value, "installTime");
			return (Criteria) this;
		}

		public Criteria andInstallTimeLessThanOrEqualTo(Date value) {
			addCriterion("install_time <=", value, "installTime");
			return (Criteria) this;
		}

		public Criteria andInstallTimeIn(List<Date> values) {
			addCriterion("install_time in", values, "installTime");
			return (Criteria) this;
		}

		public Criteria andInstallTimeNotIn(List<Date> values) {
			addCriterion("install_time not in", values, "installTime");
			return (Criteria) this;
		}

		public Criteria andInstallTimeBetween(Date value1, Date value2) {
			addCriterion("install_time between", value1, value2, "installTime");
			return (Criteria) this;
		}

		public Criteria andInstallTimeNotBetween(Date value1, Date value2) {
			addCriterion("install_time not between", value1, value2, "installTime");
			return (Criteria) this;
		}

		public Criteria andCdateIsNull() {
			addCriterion("cdate is null");
			return (Criteria) this;
		}

		public Criteria andCdateIsNotNull() {
			addCriterion("cdate is not null");
			return (Criteria) this;
		}

		public Criteria andCdateEqualTo(Date value) {
			addCriterion("cdate =", value, "cdate");
			return (Criteria) this;
		}

		public Criteria andCdateNotEqualTo(Date value) {
			addCriterion("cdate <>", value, "cdate");
			return (Criteria) this;
		}

		public Criteria andCdateGreaterThan(Date value) {
			addCriterion("cdate >", value, "cdate");
			return (Criteria) this;
		}

		public Criteria andCdateGreaterThanOrEqualTo(Date value) {
			addCriterion("cdate >=", value, "cdate");
			return (Criteria) this;
		}

		public Criteria andCdateLessThan(Date value) {
			addCriterion("cdate <", value, "cdate");
			return (Criteria) this;
		}

		public Criteria andCdateLessThanOrEqualTo(Date value) {
			addCriterion("cdate <=", value, "cdate");
			return (Criteria) this;
		}

		public Criteria andCdateIn(List<Date> values) {
			addCriterion("cdate in", values, "cdate");
			return (Criteria) this;
		}

		public Criteria andCdateNotIn(List<Date> values) {
			addCriterion("cdate not in", values, "cdate");
			return (Criteria) this;
		}

		public Criteria andCdateBetween(Date value1, Date value2) {
			addCriterion("cdate between", value1, value2, "cdate");
			return (Criteria) this;
		}

		public Criteria andCdateNotBetween(Date value1, Date value2) {
			addCriterion("cdate not between", value1, value2, "cdate");
			return (Criteria) this;
		}

		public Criteria andMdateIsNull() {
			addCriterion("mdate is null");
			return (Criteria) this;
		}

		public Criteria andMdateIsNotNull() {
			addCriterion("mdate is not null");
			return (Criteria) this;
		}

		public Criteria andMdateEqualTo(Date value) {
			addCriterion("mdate =", value, "mdate");
			return (Criteria) this;
		}

		public Criteria andMdateNotEqualTo(Date value) {
			addCriterion("mdate <>", value, "mdate");
			return (Criteria) this;
		}

		public Criteria andMdateGreaterThan(Date value) {
			addCriterion("mdate >", value, "mdate");
			return (Criteria) this;
		}

		public Criteria andMdateGreaterThanOrEqualTo(Date value) {
			addCriterion("mdate >=", value, "mdate");
			return (Criteria) this;
		}

		public Criteria andMdateLessThan(Date value) {
			addCriterion("mdate <", value, "mdate");
			return (Criteria) this;
		}

		public Criteria andMdateLessThanOrEqualTo(Date value) {
			addCriterion("mdate <=", value, "mdate");
			return (Criteria) this;
		}

		public Criteria andMdateIn(List<Date> values) {
			addCriterion("mdate in", values, "mdate");
			return (Criteria) this;
		}

		public Criteria andMdateNotIn(List<Date> values) {
			addCriterion("mdate not in", values, "mdate");
			return (Criteria) this;
		}

		public Criteria andMdateBetween(Date value1, Date value2) {
			addCriterion("mdate between", value1, value2, "mdate");
			return (Criteria) this;
		}

		public Criteria andMdateNotBetween(Date value1, Date value2) {
			addCriterion("mdate not between", value1, value2, "mdate");
			return (Criteria) this;
		}

		public Criteria andFlagIsNull() {
			addCriterion("flag is null");
			return (Criteria) this;
		}

		public Criteria andFlagIsNotNull() {
			addCriterion("flag is not null");
			return (Criteria) this;
		}

		public Criteria andFlagEqualTo(Byte value) {
			addCriterion("flag =", value, "flag");
			return (Criteria) this;
		}

		public Criteria andFlagNotEqualTo(Byte value) {
			addCriterion("flag <>", value, "flag");
			return (Criteria) this;
		}

		public Criteria andFlagGreaterThan(Byte value) {
			addCriterion("flag >", value, "flag");
			return (Criteria) this;
		}

		public Criteria andFlagGreaterThanOrEqualTo(Byte value) {
			addCriterion("flag >=", value, "flag");
			return (Criteria) this;
		}

		public Criteria andFlagLessThan(Byte value) {
			addCriterion("flag <", value, "flag");
			return (Criteria) this;
		}

		public Criteria andFlagLessThanOrEqualTo(Byte value) {
			addCriterion("flag <=", value, "flag");
			return (Criteria) this;
		}

		public Criteria andFlagIn(List<Byte> values) {
			addCriterion("flag in", values, "flag");
			return (Criteria) this;
		}

		public Criteria andFlagNotIn(List<Byte> values) {
			addCriterion("flag not in", values, "flag");
			return (Criteria) this;
		}

		public Criteria andFlagBetween(Byte value1, Byte value2) {
			addCriterion("flag between", value1, value2, "flag");
			return (Criteria) this;
		}

		public Criteria andFlagNotBetween(Byte value1, Byte value2) {
			addCriterion("flag not between", value1, value2, "flag");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNull() {
			addCriterion("remark is null");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNotNull() {
			addCriterion("remark is not null");
			return (Criteria) this;
		}

		public Criteria andRemarkEqualTo(String value) {
			addCriterion("remark =", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotEqualTo(String value) {
			addCriterion("remark <>", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThan(String value) {
			addCriterion("remark >", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThanOrEqualTo(String value) {
			addCriterion("remark >=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThan(String value) {
			addCriterion("remark <", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThanOrEqualTo(String value) {
			addCriterion("remark <=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLike(String value) {
			addCriterion("remark like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotLike(String value) {
			addCriterion("remark not like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkIn(List<String> values) {
			addCriterion("remark in", values, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotIn(List<String> values) {
			addCriterion("remark not in", values, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkBetween(String value1, String value2) {
			addCriterion("remark between", value1, value2, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotBetween(String value1, String value2) {
			addCriterion("remark not between", value1, value2, "remark");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table product_install
	 * @mbg.generated  Mon Dec 17 01:45:08 CST 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}



    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product_install
     *
     * @mbg.generated do_not_delete_during_merge Mon Dec 17 01:10:56 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}