package com.yh.tradease.stock.dao;

import com.yh.tradease.stock.entity.InStock;
import com.yh.tradease.stock.entity.InStockExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface InStockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_stock
     *
     * @mbg.generated Thu Dec 20 00:21:32 CST 2018
     */
    long countByExample(InStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_stock
     *
     * @mbg.generated Thu Dec 20 00:21:32 CST 2018
     */
    int deleteByExample(InStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_stock
     *
     * @mbg.generated Thu Dec 20 00:21:32 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_stock
     *
     * @mbg.generated Thu Dec 20 00:21:32 CST 2018
     */
    int insert(InStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_stock
     *
     * @mbg.generated Thu Dec 20 00:21:32 CST 2018
     */
    int insertSelective(InStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_stock
     *
     * @mbg.generated Thu Dec 20 00:21:32 CST 2018
     */
    List<InStock> selectByExample(InStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_stock
     *
     * @mbg.generated Thu Dec 20 00:21:32 CST 2018
     */
    InStock selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_stock
     *
     * @mbg.generated Thu Dec 20 00:21:32 CST 2018
     */
    int updateByExampleSelective(@Param("record") InStock record, @Param("example") InStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_stock
     *
     * @mbg.generated Thu Dec 20 00:21:32 CST 2018
     */
    int updateByExample(@Param("record") InStock record, @Param("example") InStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_stock
     *
     * @mbg.generated Thu Dec 20 00:21:32 CST 2018
     */
    int updateByPrimaryKeySelective(InStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_stock
     *
     * @mbg.generated Thu Dec 20 00:21:32 CST 2018
     */
    int updateByPrimaryKey(InStock record);
}