package com.yh.tradease.stock.dao;

import com.yh.tradease.stock.entity.OutStock;
import com.yh.tradease.stock.entity.OutStockExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface OutStockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_stock
     *
     * @mbg.generated Thu Dec 20 01:35:20 CST 2018
     */
    long countByExample(OutStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_stock
     *
     * @mbg.generated Thu Dec 20 01:35:20 CST 2018
     */
    int deleteByExample(OutStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_stock
     *
     * @mbg.generated Thu Dec 20 01:35:20 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_stock
     *
     * @mbg.generated Thu Dec 20 01:35:20 CST 2018
     */
    int insert(OutStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_stock
     *
     * @mbg.generated Thu Dec 20 01:35:20 CST 2018
     */
    int insertSelective(OutStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_stock
     *
     * @mbg.generated Thu Dec 20 01:35:20 CST 2018
     */
    List<OutStock> selectByExample(OutStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_stock
     *
     * @mbg.generated Thu Dec 20 01:35:20 CST 2018
     */
    OutStock selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_stock
     *
     * @mbg.generated Thu Dec 20 01:35:20 CST 2018
     */
    int updateByExampleSelective(@Param("record") OutStock record, @Param("example") OutStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_stock
     *
     * @mbg.generated Thu Dec 20 01:35:20 CST 2018
     */
    int updateByExample(@Param("record") OutStock record, @Param("example") OutStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_stock
     *
     * @mbg.generated Thu Dec 20 01:35:20 CST 2018
     */
    int updateByPrimaryKeySelective(OutStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_stock
     *
     * @mbg.generated Thu Dec 20 01:35:20 CST 2018
     */
    int updateByPrimaryKey(OutStock record);
}