package com.yh.tradease.stock.dao;

import com.yh.tradease.stock.entity.StorageInfo;
import com.yh.tradease.stock.entity.StorageInfoExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface StorageInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table storage_info
	 * @mbg.generated  Sun Dec 23 22:01:32 CST 2018
	 */
	long countByExample(StorageInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table storage_info
	 * @mbg.generated  Sun Dec 23 22:01:32 CST 2018
	 */
	int deleteByExample(StorageInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table storage_info
	 * @mbg.generated  Sun Dec 23 22:01:32 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table storage_info
	 * @mbg.generated  Sun Dec 23 22:01:32 CST 2018
	 */
	int insert(StorageInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table storage_info
	 * @mbg.generated  Sun Dec 23 22:01:32 CST 2018
	 */
	int insertSelective(StorageInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table storage_info
	 * @mbg.generated  Sun Dec 23 22:01:32 CST 2018
	 */
	List<StorageInfo> selectByExample(StorageInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table storage_info
	 * @mbg.generated  Sun Dec 23 22:01:32 CST 2018
	 */
	StorageInfo selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table storage_info
	 * @mbg.generated  Sun Dec 23 22:01:32 CST 2018
	 */
	int updateByExampleSelective(@Param("record") StorageInfo record, @Param("example") StorageInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table storage_info
	 * @mbg.generated  Sun Dec 23 22:01:32 CST 2018
	 */
	int updateByExample(@Param("record") StorageInfo record, @Param("example") StorageInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table storage_info
	 * @mbg.generated  Sun Dec 23 22:01:32 CST 2018
	 */
	int updateByPrimaryKeySelective(StorageInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table storage_info
	 * @mbg.generated  Sun Dec 23 22:01:32 CST 2018
	 */
	int updateByPrimaryKey(StorageInfo record);
}