package com.yh.tradease.system.dao;

import com.yh.tradease.system.entity.SysDic;
import com.yh.tradease.system.entity.SysDicExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface SysDicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dic
     *
     * @mbg.generated Sat Feb 02 09:17:25 CST 2019
     */
    long countByExample(SysDicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dic
     *
     * @mbg.generated Sat Feb 02 09:17:25 CST 2019
     */
    int deleteByExample(SysDicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dic
     *
     * @mbg.generated Sat Feb 02 09:17:25 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dic
     *
     * @mbg.generated Sat Feb 02 09:17:25 CST 2019
     */
    int insert(SysDic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dic
     *
     * @mbg.generated Sat Feb 02 09:17:25 CST 2019
     */
    int insertSelective(SysDic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dic
     *
     * @mbg.generated Sat Feb 02 09:17:25 CST 2019
     */
    List<SysDic> selectByExample(SysDicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dic
     *
     * @mbg.generated Sat Feb 02 09:17:25 CST 2019
     */
    SysDic selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dic
     *
     * @mbg.generated Sat Feb 02 09:17:25 CST 2019
     */
    int updateByExampleSelective(@Param("record") SysDic record, @Param("example") SysDicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dic
     *
     * @mbg.generated Sat Feb 02 09:17:25 CST 2019
     */
    int updateByExample(@Param("record") SysDic record, @Param("example") SysDicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dic
     *
     * @mbg.generated Sat Feb 02 09:17:25 CST 2019
     */
    int updateByPrimaryKeySelective(SysDic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dic
     *
     * @mbg.generated Sat Feb 02 09:17:25 CST 2019
     */
    int updateByPrimaryKey(SysDic record);

	List<String> selectBusinessNames();

	List<String> selectSubjectNames(String businessModule);
}