server:
  port: 8080
  context-path: /
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm
    time-zone: GMT+8
  resources:
    static-locations:  classpath:/static/
  datasource:
    url: jdbc:mysql://localhost:3306/tradease?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.yh.tradease.*.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  