package com.yh.tradease.product.entity;

import java.util.Date;
import java.util.List;

public class ProductModule {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_module.id
     *
     * @mbg.generated Mon Dec 24 00:38:05 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_module.name
     *
     * @mbg.generated Mon Dec 24 00:38:05 CST 2018
     */
    private String name;
    
    private String label;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_module.pid
     *
     * @mbg.generated Mon Dec 24 00:38:05 CST 2018
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_module.level
     *
     * @mbg.generated Mon Dec 24 00:38:05 CST 2018
     */
    private Integer level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_module.remark
     *
     * @mbg.generated Mon Dec 24 00:38:05 CST 2018
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_module.cdate
     *
     * @mbg.generated Mon Dec 24 00:38:05 CST 2018
     */
    private Date cdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_module.mdate
     *
     * @mbg.generated Mon Dec 24 00:38:05 CST 2018
     */
    private Date mdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_module.flag
     *
     * @mbg.generated Mon Dec 24 00:38:05 CST 2018
     */
    private Byte flag;
    
    /**
     * 子模块
     */
    private List<ProductModule> children;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_module.id
     *
     * @return the value of product_module.id
     *
     * @mbg.generated Mon Dec 24 00:38:05 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_module.id
     *
     * @param id the value for product_module.id
     *
     * @mbg.generated Mon Dec 24 00:38:05 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_module.name
     *
     * @return the value of product_module.name
     *
     * @mbg.generated Mon Dec 24 00:38:05 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_module.name
     *
     * @param name the value for product_module.name
     *
     * @mbg.generated Mon Dec 24 00:38:05 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_module.pid
     *
     * @return the value of product_module.pid
     *
     * @mbg.generated Mon Dec 24 00:38:05 CST 2018
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_module.pid
     *
     * @param pid the value for product_module.pid
     *
     * @mbg.generated Mon Dec 24 00:38:05 CST 2018
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_module.level
     *
     * @return the value of product_module.level
     *
     * @mbg.generated Mon Dec 24 00:38:05 CST 2018
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_module.level
     *
     * @param level the value for product_module.level
     *
     * @mbg.generated Mon Dec 24 00:38:05 CST 2018
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_module.remark
     *
     * @return the value of product_module.remark
     *
     * @mbg.generated Mon Dec 24 00:38:05 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_module.remark
     *
     * @param remark the value for product_module.remark
     *
     * @mbg.generated Mon Dec 24 00:38:05 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_module.cdate
     *
     * @return the value of product_module.cdate
     *
     * @mbg.generated Mon Dec 24 00:38:05 CST 2018
     */
    public Date getCdate() {
        return cdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_module.cdate
     *
     * @param cdate the value for product_module.cdate
     *
     * @mbg.generated Mon Dec 24 00:38:05 CST 2018
     */
    public void setCdate(Date cdate) {
        this.cdate = cdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_module.mdate
     *
     * @return the value of product_module.mdate
     *
     * @mbg.generated Mon Dec 24 00:38:05 CST 2018
     */
    public Date getMdate() {
        return mdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_module.mdate
     *
     * @param mdate the value for product_module.mdate
     *
     * @mbg.generated Mon Dec 24 00:38:05 CST 2018
     */
    public void setMdate(Date mdate) {
        this.mdate = mdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_module.flag
     *
     * @return the value of product_module.flag
     *
     * @mbg.generated Mon Dec 24 00:38:05 CST 2018
     */
    public Byte getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_module.flag
     *
     * @param flag the value for product_module.flag
     *
     * @mbg.generated Mon Dec 24 00:38:05 CST 2018
     */
    public void setFlag(Byte flag) {
        this.flag = flag;
    }

	public List<ProductModule> getChildren() {
		return children;
	}

	public void setModules(List<ProductModule> children) {
		this.children = children;
	}

	public String getLabel() {
		return label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	public void setChildren(List<ProductModule> children) {
		this.children = children;
	}
    
    
}