package com.yh.tradease.finance.dao;

import com.yh.tradease.finance.entity.OrderBill;
import com.yh.tradease.finance.entity.OrderBillExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface OrderBillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_bill
     *
     * @mbg.generated Wed Dec 26 00:49:03 CST 2018
     */
    long countByExample(OrderBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_bill
     *
     * @mbg.generated Wed Dec 26 00:49:03 CST 2018
     */
    int deleteByExample(OrderBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_bill
     *
     * @mbg.generated Wed Dec 26 00:49:03 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_bill
     *
     * @mbg.generated Wed Dec 26 00:49:03 CST 2018
     */
    int insert(OrderBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_bill
     *
     * @mbg.generated Wed Dec 26 00:49:03 CST 2018
     */
    int insertSelective(OrderBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_bill
     *
     * @mbg.generated Wed Dec 26 00:49:03 CST 2018
     */
    List<OrderBill> selectByExample(OrderBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_bill
     *
     * @mbg.generated Wed Dec 26 00:49:03 CST 2018
     */
    OrderBill selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_bill
     *
     * @mbg.generated Wed Dec 26 00:49:03 CST 2018
     */
    int updateByExampleSelective(@Param("record") OrderBill record, @Param("example") OrderBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_bill
     *
     * @mbg.generated Wed Dec 26 00:49:03 CST 2018
     */
    int updateByExample(@Param("record") OrderBill record, @Param("example") OrderBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_bill
     *
     * @mbg.generated Wed Dec 26 00:49:03 CST 2018
     */
    int updateByPrimaryKeySelective(OrderBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_bill
     *
     * @mbg.generated Wed Dec 26 00:49:03 CST 2018
     */
    int updateByPrimaryKey(OrderBill record);
}