package com.yh.tradease.sales.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SaleRecordExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sale_record
	 * @mbg.generated  Mon Dec 10 23:32:09 CST 2018
	 */
	protected String orderByClause;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sale_record
	 * @mbg.generated  Mon Dec 10 23:32:09 CST 2018
	 */
	protected boolean distinct;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sale_record
	 * @mbg.generated  Mon Dec 10 23:32:09 CST 2018
	 */
	protected List<Criteria> oredCriteria;


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sale_record
	 * @mbg.generated  Mon Dec 10 23:32:09 CST 2018
	 */
	public SaleRecordExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sale_record
	 * @mbg.generated  Mon Dec 10 23:32:09 CST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sale_record
	 * @mbg.generated  Mon Dec 10 23:32:09 CST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sale_record
	 * @mbg.generated  Mon Dec 10 23:32:09 CST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sale_record
	 * @mbg.generated  Mon Dec 10 23:32:09 CST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sale_record
	 * @mbg.generated  Mon Dec 10 23:32:09 CST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sale_record
	 * @mbg.generated  Mon Dec 10 23:32:09 CST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sale_record
	 * @mbg.generated  Mon Dec 10 23:32:09 CST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sale_record
	 * @mbg.generated  Mon Dec 10 23:32:09 CST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sale_record
	 * @mbg.generated  Mon Dec 10 23:32:09 CST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sale_record
	 * @mbg.generated  Mon Dec 10 23:32:09 CST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}



	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table sale_record
	 * @mbg.generated  Mon Dec 10 23:32:09 CST 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andBrokerIsNull() {
			addCriterion("broker is null");
			return (Criteria) this;
		}

		public Criteria andBrokerIsNotNull() {
			addCriterion("broker is not null");
			return (Criteria) this;
		}

		public Criteria andBrokerEqualTo(Integer value) {
			addCriterion("broker =", value, "broker");
			return (Criteria) this;
		}

		public Criteria andBrokerNotEqualTo(Integer value) {
			addCriterion("broker <>", value, "broker");
			return (Criteria) this;
		}

		public Criteria andBrokerGreaterThan(Integer value) {
			addCriterion("broker >", value, "broker");
			return (Criteria) this;
		}

		public Criteria andBrokerGreaterThanOrEqualTo(Integer value) {
			addCriterion("broker >=", value, "broker");
			return (Criteria) this;
		}

		public Criteria andBrokerLessThan(Integer value) {
			addCriterion("broker <", value, "broker");
			return (Criteria) this;
		}

		public Criteria andBrokerLessThanOrEqualTo(Integer value) {
			addCriterion("broker <=", value, "broker");
			return (Criteria) this;
		}

		public Criteria andBrokerIn(List<Integer> values) {
			addCriterion("broker in", values, "broker");
			return (Criteria) this;
		}

		public Criteria andBrokerNotIn(List<Integer> values) {
			addCriterion("broker not in", values, "broker");
			return (Criteria) this;
		}

		public Criteria andBrokerBetween(Integer value1, Integer value2) {
			addCriterion("broker between", value1, value2, "broker");
			return (Criteria) this;
		}

		public Criteria andBrokerNotBetween(Integer value1, Integer value2) {
			addCriterion("broker not between", value1, value2, "broker");
			return (Criteria) this;
		}

		public Criteria andTotalPriceIsNull() {
			addCriterion("total_price is null");
			return (Criteria) this;
		}

		public Criteria andTotalPriceIsNotNull() {
			addCriterion("total_price is not null");
			return (Criteria) this;
		}

		public Criteria andTotalPriceEqualTo(Double value) {
			addCriterion("total_price =", value, "totalPrice");
			return (Criteria) this;
		}

		public Criteria andTotalPriceNotEqualTo(Double value) {
			addCriterion("total_price <>", value, "totalPrice");
			return (Criteria) this;
		}

		public Criteria andTotalPriceGreaterThan(Double value) {
			addCriterion("total_price >", value, "totalPrice");
			return (Criteria) this;
		}

		public Criteria andTotalPriceGreaterThanOrEqualTo(Double value) {
			addCriterion("total_price >=", value, "totalPrice");
			return (Criteria) this;
		}

		public Criteria andTotalPriceLessThan(Double value) {
			addCriterion("total_price <", value, "totalPrice");
			return (Criteria) this;
		}

		public Criteria andTotalPriceLessThanOrEqualTo(Double value) {
			addCriterion("total_price <=", value, "totalPrice");
			return (Criteria) this;
		}

		public Criteria andTotalPriceIn(List<Double> values) {
			addCriterion("total_price in", values, "totalPrice");
			return (Criteria) this;
		}

		public Criteria andTotalPriceNotIn(List<Double> values) {
			addCriterion("total_price not in", values, "totalPrice");
			return (Criteria) this;
		}

		public Criteria andTotalPriceBetween(Double value1, Double value2) {
			addCriterion("total_price between", value1, value2, "totalPrice");
			return (Criteria) this;
		}

		public Criteria andTotalPriceNotBetween(Double value1, Double value2) {
			addCriterion("total_price not between", value1, value2, "totalPrice");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("name is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("name is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("name =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("name <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("name >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("name >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("name <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("name <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("name like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("name not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("name in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("name not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("name between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("name not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andTypeIsNull() {
			addCriterion("type is null");
			return (Criteria) this;
		}

		public Criteria andTypeIsNotNull() {
			addCriterion("type is not null");
			return (Criteria) this;
		}

		public Criteria andTypeEqualTo(Byte value) {
			addCriterion("type =", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotEqualTo(Byte value) {
			addCriterion("type <>", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThan(Byte value) {
			addCriterion("type >", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThanOrEqualTo(Byte value) {
			addCriterion("type >=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThan(Byte value) {
			addCriterion("type <", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThanOrEqualTo(Byte value) {
			addCriterion("type <=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeIn(List<Byte> values) {
			addCriterion("type in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotIn(List<Byte> values) {
			addCriterion("type not in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeBetween(Byte value1, Byte value2) {
			addCriterion("type between", value1, value2, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotBetween(Byte value1, Byte value2) {
			addCriterion("type not between", value1, value2, "type");
			return (Criteria) this;
		}

		public Criteria andRealPriceIsNull() {
			addCriterion("real_price is null");
			return (Criteria) this;
		}

		public Criteria andRealPriceIsNotNull() {
			addCriterion("real_price is not null");
			return (Criteria) this;
		}

		public Criteria andRealPriceEqualTo(Double value) {
			addCriterion("real_price =", value, "realPrice");
			return (Criteria) this;
		}

		public Criteria andRealPriceNotEqualTo(Double value) {
			addCriterion("real_price <>", value, "realPrice");
			return (Criteria) this;
		}

		public Criteria andRealPriceGreaterThan(Double value) {
			addCriterion("real_price >", value, "realPrice");
			return (Criteria) this;
		}

		public Criteria andRealPriceGreaterThanOrEqualTo(Double value) {
			addCriterion("real_price >=", value, "realPrice");
			return (Criteria) this;
		}

		public Criteria andRealPriceLessThan(Double value) {
			addCriterion("real_price <", value, "realPrice");
			return (Criteria) this;
		}

		public Criteria andRealPriceLessThanOrEqualTo(Double value) {
			addCriterion("real_price <=", value, "realPrice");
			return (Criteria) this;
		}

		public Criteria andRealPriceIn(List<Double> values) {
			addCriterion("real_price in", values, "realPrice");
			return (Criteria) this;
		}

		public Criteria andRealPriceNotIn(List<Double> values) {
			addCriterion("real_price not in", values, "realPrice");
			return (Criteria) this;
		}

		public Criteria andRealPriceBetween(Double value1, Double value2) {
			addCriterion("real_price between", value1, value2, "realPrice");
			return (Criteria) this;
		}

		public Criteria andRealPriceNotBetween(Double value1, Double value2) {
			addCriterion("real_price not between", value1, value2, "realPrice");
			return (Criteria) this;
		}

		public Criteria andPayedIsNull() {
			addCriterion("payed is null");
			return (Criteria) this;
		}

		public Criteria andPayedIsNotNull() {
			addCriterion("payed is not null");
			return (Criteria) this;
		}

		public Criteria andPayedEqualTo(Double value) {
			addCriterion("payed =", value, "payed");
			return (Criteria) this;
		}

		public Criteria andPayedNotEqualTo(Double value) {
			addCriterion("payed <>", value, "payed");
			return (Criteria) this;
		}

		public Criteria andPayedGreaterThan(Double value) {
			addCriterion("payed >", value, "payed");
			return (Criteria) this;
		}

		public Criteria andPayedGreaterThanOrEqualTo(Double value) {
			addCriterion("payed >=", value, "payed");
			return (Criteria) this;
		}

		public Criteria andPayedLessThan(Double value) {
			addCriterion("payed <", value, "payed");
			return (Criteria) this;
		}

		public Criteria andPayedLessThanOrEqualTo(Double value) {
			addCriterion("payed <=", value, "payed");
			return (Criteria) this;
		}

		public Criteria andPayedIn(List<Double> values) {
			addCriterion("payed in", values, "payed");
			return (Criteria) this;
		}

		public Criteria andPayedNotIn(List<Double> values) {
			addCriterion("payed not in", values, "payed");
			return (Criteria) this;
		}

		public Criteria andPayedBetween(Double value1, Double value2) {
			addCriterion("payed between", value1, value2, "payed");
			return (Criteria) this;
		}

		public Criteria andPayedNotBetween(Double value1, Double value2) {
			addCriterion("payed not between", value1, value2, "payed");
			return (Criteria) this;
		}

		public Criteria andUnpayedIsNull() {
			addCriterion("unpayed is null");
			return (Criteria) this;
		}

		public Criteria andUnpayedIsNotNull() {
			addCriterion("unpayed is not null");
			return (Criteria) this;
		}

		public Criteria andUnpayedEqualTo(Double value) {
			addCriterion("unpayed =", value, "unpayed");
			return (Criteria) this;
		}

		public Criteria andUnpayedNotEqualTo(Double value) {
			addCriterion("unpayed <>", value, "unpayed");
			return (Criteria) this;
		}

		public Criteria andUnpayedGreaterThan(Double value) {
			addCriterion("unpayed >", value, "unpayed");
			return (Criteria) this;
		}

		public Criteria andUnpayedGreaterThanOrEqualTo(Double value) {
			addCriterion("unpayed >=", value, "unpayed");
			return (Criteria) this;
		}

		public Criteria andUnpayedLessThan(Double value) {
			addCriterion("unpayed <", value, "unpayed");
			return (Criteria) this;
		}

		public Criteria andUnpayedLessThanOrEqualTo(Double value) {
			addCriterion("unpayed <=", value, "unpayed");
			return (Criteria) this;
		}

		public Criteria andUnpayedIn(List<Double> values) {
			addCriterion("unpayed in", values, "unpayed");
			return (Criteria) this;
		}

		public Criteria andUnpayedNotIn(List<Double> values) {
			addCriterion("unpayed not in", values, "unpayed");
			return (Criteria) this;
		}

		public Criteria andUnpayedBetween(Double value1, Double value2) {
			addCriterion("unpayed between", value1, value2, "unpayed");
			return (Criteria) this;
		}

		public Criteria andUnpayedNotBetween(Double value1, Double value2) {
			addCriterion("unpayed not between", value1, value2, "unpayed");
			return (Criteria) this;
		}

		public Criteria andBuyerIsNull() {
			addCriterion("buyer is null");
			return (Criteria) this;
		}

		public Criteria andBuyerIsNotNull() {
			addCriterion("buyer is not null");
			return (Criteria) this;
		}

		public Criteria andBuyerEqualTo(String value) {
			addCriterion("buyer =", value, "buyer");
			return (Criteria) this;
		}

		public Criteria andBuyerNotEqualTo(String value) {
			addCriterion("buyer <>", value, "buyer");
			return (Criteria) this;
		}

		public Criteria andBuyerGreaterThan(String value) {
			addCriterion("buyer >", value, "buyer");
			return (Criteria) this;
		}

		public Criteria andBuyerGreaterThanOrEqualTo(String value) {
			addCriterion("buyer >=", value, "buyer");
			return (Criteria) this;
		}

		public Criteria andBuyerLessThan(String value) {
			addCriterion("buyer <", value, "buyer");
			return (Criteria) this;
		}

		public Criteria andBuyerLessThanOrEqualTo(String value) {
			addCriterion("buyer <=", value, "buyer");
			return (Criteria) this;
		}

		public Criteria andBuyerLike(String value) {
			addCriterion("buyer like", value, "buyer");
			return (Criteria) this;
		}

		public Criteria andBuyerNotLike(String value) {
			addCriterion("buyer not like", value, "buyer");
			return (Criteria) this;
		}

		public Criteria andBuyerIn(List<String> values) {
			addCriterion("buyer in", values, "buyer");
			return (Criteria) this;
		}

		public Criteria andBuyerNotIn(List<String> values) {
			addCriterion("buyer not in", values, "buyer");
			return (Criteria) this;
		}

		public Criteria andBuyerBetween(String value1, String value2) {
			addCriterion("buyer between", value1, value2, "buyer");
			return (Criteria) this;
		}

		public Criteria andBuyerNotBetween(String value1, String value2) {
			addCriterion("buyer not between", value1, value2, "buyer");
			return (Criteria) this;
		}

		public Criteria andBuyerPhoneIsNull() {
			addCriterion("buyer_phone is null");
			return (Criteria) this;
		}

		public Criteria andBuyerPhoneIsNotNull() {
			addCriterion("buyer_phone is not null");
			return (Criteria) this;
		}

		public Criteria andBuyerPhoneEqualTo(String value) {
			addCriterion("buyer_phone =", value, "buyerPhone");
			return (Criteria) this;
		}

		public Criteria andBuyerPhoneNotEqualTo(String value) {
			addCriterion("buyer_phone <>", value, "buyerPhone");
			return (Criteria) this;
		}

		public Criteria andBuyerPhoneGreaterThan(String value) {
			addCriterion("buyer_phone >", value, "buyerPhone");
			return (Criteria) this;
		}

		public Criteria andBuyerPhoneGreaterThanOrEqualTo(String value) {
			addCriterion("buyer_phone >=", value, "buyerPhone");
			return (Criteria) this;
		}

		public Criteria andBuyerPhoneLessThan(String value) {
			addCriterion("buyer_phone <", value, "buyerPhone");
			return (Criteria) this;
		}

		public Criteria andBuyerPhoneLessThanOrEqualTo(String value) {
			addCriterion("buyer_phone <=", value, "buyerPhone");
			return (Criteria) this;
		}

		public Criteria andBuyerPhoneLike(String value) {
			addCriterion("buyer_phone like", value, "buyerPhone");
			return (Criteria) this;
		}

		public Criteria andBuyerPhoneNotLike(String value) {
			addCriterion("buyer_phone not like", value, "buyerPhone");
			return (Criteria) this;
		}

		public Criteria andBuyerPhoneIn(List<String> values) {
			addCriterion("buyer_phone in", values, "buyerPhone");
			return (Criteria) this;
		}

		public Criteria andBuyerPhoneNotIn(List<String> values) {
			addCriterion("buyer_phone not in", values, "buyerPhone");
			return (Criteria) this;
		}

		public Criteria andBuyerPhoneBetween(String value1, String value2) {
			addCriterion("buyer_phone between", value1, value2, "buyerPhone");
			return (Criteria) this;
		}

		public Criteria andBuyerPhoneNotBetween(String value1, String value2) {
			addCriterion("buyer_phone not between", value1, value2, "buyerPhone");
			return (Criteria) this;
		}

		public Criteria andBuyTimeIsNull() {
			addCriterion("buy_time is null");
			return (Criteria) this;
		}

		public Criteria andBuyTimeIsNotNull() {
			addCriterion("buy_time is not null");
			return (Criteria) this;
		}

		public Criteria andBuyTimeEqualTo(Date value) {
			addCriterion("buy_time =", value, "buyTime");
			return (Criteria) this;
		}

		public Criteria andBuyTimeNotEqualTo(Date value) {
			addCriterion("buy_time <>", value, "buyTime");
			return (Criteria) this;
		}

		public Criteria andBuyTimeGreaterThan(Date value) {
			addCriterion("buy_time >", value, "buyTime");
			return (Criteria) this;
		}

		public Criteria andBuyTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("buy_time >=", value, "buyTime");
			return (Criteria) this;
		}

		public Criteria andBuyTimeLessThan(Date value) {
			addCriterion("buy_time <", value, "buyTime");
			return (Criteria) this;
		}

		public Criteria andBuyTimeLessThanOrEqualTo(Date value) {
			addCriterion("buy_time <=", value, "buyTime");
			return (Criteria) this;
		}

		public Criteria andBuyTimeIn(List<Date> values) {
			addCriterion("buy_time in", values, "buyTime");
			return (Criteria) this;
		}

		public Criteria andBuyTimeNotIn(List<Date> values) {
			addCriterion("buy_time not in", values, "buyTime");
			return (Criteria) this;
		}

		public Criteria andBuyTimeBetween(Date value1, Date value2) {
			addCriterion("buy_time between", value1, value2, "buyTime");
			return (Criteria) this;
		}

		public Criteria andBuyTimeNotBetween(Date value1, Date value2) {
			addCriterion("buy_time not between", value1, value2, "buyTime");
			return (Criteria) this;
		}

		public Criteria andReceiverIsNull() {
			addCriterion("receiver is null");
			return (Criteria) this;
		}

		public Criteria andReceiverIsNotNull() {
			addCriterion("receiver is not null");
			return (Criteria) this;
		}

		public Criteria andReceiverEqualTo(String value) {
			addCriterion("receiver =", value, "receiver");
			return (Criteria) this;
		}

		public Criteria andReceiverNotEqualTo(String value) {
			addCriterion("receiver <>", value, "receiver");
			return (Criteria) this;
		}

		public Criteria andReceiverGreaterThan(String value) {
			addCriterion("receiver >", value, "receiver");
			return (Criteria) this;
		}

		public Criteria andReceiverGreaterThanOrEqualTo(String value) {
			addCriterion("receiver >=", value, "receiver");
			return (Criteria) this;
		}

		public Criteria andReceiverLessThan(String value) {
			addCriterion("receiver <", value, "receiver");
			return (Criteria) this;
		}

		public Criteria andReceiverLessThanOrEqualTo(String value) {
			addCriterion("receiver <=", value, "receiver");
			return (Criteria) this;
		}

		public Criteria andReceiverLike(String value) {
			addCriterion("receiver like", value, "receiver");
			return (Criteria) this;
		}

		public Criteria andReceiverNotLike(String value) {
			addCriterion("receiver not like", value, "receiver");
			return (Criteria) this;
		}

		public Criteria andReceiverIn(List<String> values) {
			addCriterion("receiver in", values, "receiver");
			return (Criteria) this;
		}

		public Criteria andReceiverNotIn(List<String> values) {
			addCriterion("receiver not in", values, "receiver");
			return (Criteria) this;
		}

		public Criteria andReceiverBetween(String value1, String value2) {
			addCriterion("receiver between", value1, value2, "receiver");
			return (Criteria) this;
		}

		public Criteria andReceiverNotBetween(String value1, String value2) {
			addCriterion("receiver not between", value1, value2, "receiver");
			return (Criteria) this;
		}

		public Criteria andReceiverPhoneIsNull() {
			addCriterion("receiver_phone is null");
			return (Criteria) this;
		}

		public Criteria andReceiverPhoneIsNotNull() {
			addCriterion("receiver_phone is not null");
			return (Criteria) this;
		}

		public Criteria andReceiverPhoneEqualTo(String value) {
			addCriterion("receiver_phone =", value, "receiverPhone");
			return (Criteria) this;
		}

		public Criteria andReceiverPhoneNotEqualTo(String value) {
			addCriterion("receiver_phone <>", value, "receiverPhone");
			return (Criteria) this;
		}

		public Criteria andReceiverPhoneGreaterThan(String value) {
			addCriterion("receiver_phone >", value, "receiverPhone");
			return (Criteria) this;
		}

		public Criteria andReceiverPhoneGreaterThanOrEqualTo(String value) {
			addCriterion("receiver_phone >=", value, "receiverPhone");
			return (Criteria) this;
		}

		public Criteria andReceiverPhoneLessThan(String value) {
			addCriterion("receiver_phone <", value, "receiverPhone");
			return (Criteria) this;
		}

		public Criteria andReceiverPhoneLessThanOrEqualTo(String value) {
			addCriterion("receiver_phone <=", value, "receiverPhone");
			return (Criteria) this;
		}

		public Criteria andReceiverPhoneLike(String value) {
			addCriterion("receiver_phone like", value, "receiverPhone");
			return (Criteria) this;
		}

		public Criteria andReceiverPhoneNotLike(String value) {
			addCriterion("receiver_phone not like", value, "receiverPhone");
			return (Criteria) this;
		}

		public Criteria andReceiverPhoneIn(List<String> values) {
			addCriterion("receiver_phone in", values, "receiverPhone");
			return (Criteria) this;
		}

		public Criteria andReceiverPhoneNotIn(List<String> values) {
			addCriterion("receiver_phone not in", values, "receiverPhone");
			return (Criteria) this;
		}

		public Criteria andReceiverPhoneBetween(String value1, String value2) {
			addCriterion("receiver_phone between", value1, value2, "receiverPhone");
			return (Criteria) this;
		}

		public Criteria andReceiverPhoneNotBetween(String value1, String value2) {
			addCriterion("receiver_phone not between", value1, value2, "receiverPhone");
			return (Criteria) this;
		}

		public Criteria andCustomerTypeIsNull() {
			addCriterion("customer_type is null");
			return (Criteria) this;
		}

		public Criteria andCustomerTypeIsNotNull() {
			addCriterion("customer_type is not null");
			return (Criteria) this;
		}

		public Criteria andCustomerTypeEqualTo(Byte value) {
			addCriterion("customer_type =", value, "customerType");
			return (Criteria) this;
		}

		public Criteria andCustomerTypeNotEqualTo(Byte value) {
			addCriterion("customer_type <>", value, "customerType");
			return (Criteria) this;
		}

		public Criteria andCustomerTypeGreaterThan(Byte value) {
			addCriterion("customer_type >", value, "customerType");
			return (Criteria) this;
		}

		public Criteria andCustomerTypeGreaterThanOrEqualTo(Byte value) {
			addCriterion("customer_type >=", value, "customerType");
			return (Criteria) this;
		}

		public Criteria andCustomerTypeLessThan(Byte value) {
			addCriterion("customer_type <", value, "customerType");
			return (Criteria) this;
		}

		public Criteria andCustomerTypeLessThanOrEqualTo(Byte value) {
			addCriterion("customer_type <=", value, "customerType");
			return (Criteria) this;
		}

		public Criteria andCustomerTypeIn(List<Byte> values) {
			addCriterion("customer_type in", values, "customerType");
			return (Criteria) this;
		}

		public Criteria andCustomerTypeNotIn(List<Byte> values) {
			addCriterion("customer_type not in", values, "customerType");
			return (Criteria) this;
		}

		public Criteria andCustomerTypeBetween(Byte value1, Byte value2) {
			addCriterion("customer_type between", value1, value2, "customerType");
			return (Criteria) this;
		}

		public Criteria andCustomerTypeNotBetween(Byte value1, Byte value2) {
			addCriterion("customer_type not between", value1, value2, "customerType");
			return (Criteria) this;
		}

		public Criteria andDeliveryTimeIsNull() {
			addCriterion("delivery_time is null");
			return (Criteria) this;
		}

		public Criteria andDeliveryTimeIsNotNull() {
			addCriterion("delivery_time is not null");
			return (Criteria) this;
		}

		public Criteria andDeliveryTimeEqualTo(Date value) {
			addCriterion("delivery_time =", value, "deliveryTime");
			return (Criteria) this;
		}

		public Criteria andDeliveryTimeNotEqualTo(Date value) {
			addCriterion("delivery_time <>", value, "deliveryTime");
			return (Criteria) this;
		}

		public Criteria andDeliveryTimeGreaterThan(Date value) {
			addCriterion("delivery_time >", value, "deliveryTime");
			return (Criteria) this;
		}

		public Criteria andDeliveryTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("delivery_time >=", value, "deliveryTime");
			return (Criteria) this;
		}

		public Criteria andDeliveryTimeLessThan(Date value) {
			addCriterion("delivery_time <", value, "deliveryTime");
			return (Criteria) this;
		}

		public Criteria andDeliveryTimeLessThanOrEqualTo(Date value) {
			addCriterion("delivery_time <=", value, "deliveryTime");
			return (Criteria) this;
		}

		public Criteria andDeliveryTimeIn(List<Date> values) {
			addCriterion("delivery_time in", values, "deliveryTime");
			return (Criteria) this;
		}

		public Criteria andDeliveryTimeNotIn(List<Date> values) {
			addCriterion("delivery_time not in", values, "deliveryTime");
			return (Criteria) this;
		}

		public Criteria andDeliveryTimeBetween(Date value1, Date value2) {
			addCriterion("delivery_time between", value1, value2, "deliveryTime");
			return (Criteria) this;
		}

		public Criteria andDeliveryTimeNotBetween(Date value1, Date value2) {
			addCriterion("delivery_time not between", value1, value2, "deliveryTime");
			return (Criteria) this;
		}

		public Criteria andDeliveryAddressIsNull() {
			addCriterion("delivery_address is null");
			return (Criteria) this;
		}

		public Criteria andDeliveryAddressIsNotNull() {
			addCriterion("delivery_address is not null");
			return (Criteria) this;
		}

		public Criteria andDeliveryAddressEqualTo(String value) {
			addCriterion("delivery_address =", value, "deliveryAddress");
			return (Criteria) this;
		}

		public Criteria andDeliveryAddressNotEqualTo(String value) {
			addCriterion("delivery_address <>", value, "deliveryAddress");
			return (Criteria) this;
		}

		public Criteria andDeliveryAddressGreaterThan(String value) {
			addCriterion("delivery_address >", value, "deliveryAddress");
			return (Criteria) this;
		}

		public Criteria andDeliveryAddressGreaterThanOrEqualTo(String value) {
			addCriterion("delivery_address >=", value, "deliveryAddress");
			return (Criteria) this;
		}

		public Criteria andDeliveryAddressLessThan(String value) {
			addCriterion("delivery_address <", value, "deliveryAddress");
			return (Criteria) this;
		}

		public Criteria andDeliveryAddressLessThanOrEqualTo(String value) {
			addCriterion("delivery_address <=", value, "deliveryAddress");
			return (Criteria) this;
		}

		public Criteria andDeliveryAddressLike(String value) {
			addCriterion("delivery_address like", value, "deliveryAddress");
			return (Criteria) this;
		}

		public Criteria andDeliveryAddressNotLike(String value) {
			addCriterion("delivery_address not like", value, "deliveryAddress");
			return (Criteria) this;
		}

		public Criteria andDeliveryAddressIn(List<String> values) {
			addCriterion("delivery_address in", values, "deliveryAddress");
			return (Criteria) this;
		}

		public Criteria andDeliveryAddressNotIn(List<String> values) {
			addCriterion("delivery_address not in", values, "deliveryAddress");
			return (Criteria) this;
		}

		public Criteria andDeliveryAddressBetween(String value1, String value2) {
			addCriterion("delivery_address between", value1, value2, "deliveryAddress");
			return (Criteria) this;
		}

		public Criteria andDeliveryAddressNotBetween(String value1, String value2) {
			addCriterion("delivery_address not between", value1, value2, "deliveryAddress");
			return (Criteria) this;
		}

		public Criteria andServiceStatusIsNull() {
			addCriterion("service_status is null");
			return (Criteria) this;
		}

		public Criteria andServiceStatusIsNotNull() {
			addCriterion("service_status is not null");
			return (Criteria) this;
		}

		public Criteria andServiceStatusEqualTo(Byte value) {
			addCriterion("service_status =", value, "serviceStatus");
			return (Criteria) this;
		}

		public Criteria andServiceStatusNotEqualTo(Byte value) {
			addCriterion("service_status <>", value, "serviceStatus");
			return (Criteria) this;
		}

		public Criteria andServiceStatusGreaterThan(Byte value) {
			addCriterion("service_status >", value, "serviceStatus");
			return (Criteria) this;
		}

		public Criteria andServiceStatusGreaterThanOrEqualTo(Byte value) {
			addCriterion("service_status >=", value, "serviceStatus");
			return (Criteria) this;
		}

		public Criteria andServiceStatusLessThan(Byte value) {
			addCriterion("service_status <", value, "serviceStatus");
			return (Criteria) this;
		}

		public Criteria andServiceStatusLessThanOrEqualTo(Byte value) {
			addCriterion("service_status <=", value, "serviceStatus");
			return (Criteria) this;
		}

		public Criteria andServiceStatusIn(List<Byte> values) {
			addCriterion("service_status in", values, "serviceStatus");
			return (Criteria) this;
		}

		public Criteria andServiceStatusNotIn(List<Byte> values) {
			addCriterion("service_status not in", values, "serviceStatus");
			return (Criteria) this;
		}

		public Criteria andServiceStatusBetween(Byte value1, Byte value2) {
			addCriterion("service_status between", value1, value2, "serviceStatus");
			return (Criteria) this;
		}

		public Criteria andServiceStatusNotBetween(Byte value1, Byte value2) {
			addCriterion("service_status not between", value1, value2, "serviceStatus");
			return (Criteria) this;
		}

		public Criteria andPayStatusIsNull() {
			addCriterion("pay_status is null");
			return (Criteria) this;
		}

		public Criteria andPayStatusIsNotNull() {
			addCriterion("pay_status is not null");
			return (Criteria) this;
		}

		public Criteria andPayStatusEqualTo(Byte value) {
			addCriterion("pay_status =", value, "payStatus");
			return (Criteria) this;
		}

		public Criteria andPayStatusNotEqualTo(Byte value) {
			addCriterion("pay_status <>", value, "payStatus");
			return (Criteria) this;
		}

		public Criteria andPayStatusGreaterThan(Byte value) {
			addCriterion("pay_status >", value, "payStatus");
			return (Criteria) this;
		}

		public Criteria andPayStatusGreaterThanOrEqualTo(Byte value) {
			addCriterion("pay_status >=", value, "payStatus");
			return (Criteria) this;
		}

		public Criteria andPayStatusLessThan(Byte value) {
			addCriterion("pay_status <", value, "payStatus");
			return (Criteria) this;
		}

		public Criteria andPayStatusLessThanOrEqualTo(Byte value) {
			addCriterion("pay_status <=", value, "payStatus");
			return (Criteria) this;
		}

		public Criteria andPayStatusIn(List<Byte> values) {
			addCriterion("pay_status in", values, "payStatus");
			return (Criteria) this;
		}

		public Criteria andPayStatusNotIn(List<Byte> values) {
			addCriterion("pay_status not in", values, "payStatus");
			return (Criteria) this;
		}

		public Criteria andPayStatusBetween(Byte value1, Byte value2) {
			addCriterion("pay_status between", value1, value2, "payStatus");
			return (Criteria) this;
		}

		public Criteria andPayStatusNotBetween(Byte value1, Byte value2) {
			addCriterion("pay_status not between", value1, value2, "payStatus");
			return (Criteria) this;
		}

		public Criteria andCdateIsNull() {
			addCriterion("cdate is null");
			return (Criteria) this;
		}

		public Criteria andCdateIsNotNull() {
			addCriterion("cdate is not null");
			return (Criteria) this;
		}

		public Criteria andCdateEqualTo(Date value) {
			addCriterion("cdate =", value, "cdate");
			return (Criteria) this;
		}

		public Criteria andCdateNotEqualTo(Date value) {
			addCriterion("cdate <>", value, "cdate");
			return (Criteria) this;
		}

		public Criteria andCdateGreaterThan(Date value) {
			addCriterion("cdate >", value, "cdate");
			return (Criteria) this;
		}

		public Criteria andCdateGreaterThanOrEqualTo(Date value) {
			addCriterion("cdate >=", value, "cdate");
			return (Criteria) this;
		}

		public Criteria andCdateLessThan(Date value) {
			addCriterion("cdate <", value, "cdate");
			return (Criteria) this;
		}

		public Criteria andCdateLessThanOrEqualTo(Date value) {
			addCriterion("cdate <=", value, "cdate");
			return (Criteria) this;
		}

		public Criteria andCdateIn(List<Date> values) {
			addCriterion("cdate in", values, "cdate");
			return (Criteria) this;
		}

		public Criteria andCdateNotIn(List<Date> values) {
			addCriterion("cdate not in", values, "cdate");
			return (Criteria) this;
		}

		public Criteria andCdateBetween(Date value1, Date value2) {
			addCriterion("cdate between", value1, value2, "cdate");
			return (Criteria) this;
		}

		public Criteria andCdateNotBetween(Date value1, Date value2) {
			addCriterion("cdate not between", value1, value2, "cdate");
			return (Criteria) this;
		}

		public Criteria andMdateIsNull() {
			addCriterion("mdate is null");
			return (Criteria) this;
		}

		public Criteria andMdateIsNotNull() {
			addCriterion("mdate is not null");
			return (Criteria) this;
		}

		public Criteria andMdateEqualTo(Date value) {
			addCriterion("mdate =", value, "mdate");
			return (Criteria) this;
		}

		public Criteria andMdateNotEqualTo(Date value) {
			addCriterion("mdate <>", value, "mdate");
			return (Criteria) this;
		}

		public Criteria andMdateGreaterThan(Date value) {
			addCriterion("mdate >", value, "mdate");
			return (Criteria) this;
		}

		public Criteria andMdateGreaterThanOrEqualTo(Date value) {
			addCriterion("mdate >=", value, "mdate");
			return (Criteria) this;
		}

		public Criteria andMdateLessThan(Date value) {
			addCriterion("mdate <", value, "mdate");
			return (Criteria) this;
		}

		public Criteria andMdateLessThanOrEqualTo(Date value) {
			addCriterion("mdate <=", value, "mdate");
			return (Criteria) this;
		}

		public Criteria andMdateIn(List<Date> values) {
			addCriterion("mdate in", values, "mdate");
			return (Criteria) this;
		}

		public Criteria andMdateNotIn(List<Date> values) {
			addCriterion("mdate not in", values, "mdate");
			return (Criteria) this;
		}

		public Criteria andMdateBetween(Date value1, Date value2) {
			addCriterion("mdate between", value1, value2, "mdate");
			return (Criteria) this;
		}

		public Criteria andMdateNotBetween(Date value1, Date value2) {
			addCriterion("mdate not between", value1, value2, "mdate");
			return (Criteria) this;
		}

		public Criteria andFlagIsNull() {
			addCriterion("flag is null");
			return (Criteria) this;
		}

		public Criteria andFlagIsNotNull() {
			addCriterion("flag is not null");
			return (Criteria) this;
		}

		public Criteria andFlagEqualTo(Byte value) {
			addCriterion("flag =", value, "flag");
			return (Criteria) this;
		}

		public Criteria andFlagNotEqualTo(Byte value) {
			addCriterion("flag <>", value, "flag");
			return (Criteria) this;
		}

		public Criteria andFlagGreaterThan(Byte value) {
			addCriterion("flag >", value, "flag");
			return (Criteria) this;
		}

		public Criteria andFlagGreaterThanOrEqualTo(Byte value) {
			addCriterion("flag >=", value, "flag");
			return (Criteria) this;
		}

		public Criteria andFlagLessThan(Byte value) {
			addCriterion("flag <", value, "flag");
			return (Criteria) this;
		}

		public Criteria andFlagLessThanOrEqualTo(Byte value) {
			addCriterion("flag <=", value, "flag");
			return (Criteria) this;
		}

		public Criteria andFlagIn(List<Byte> values) {
			addCriterion("flag in", values, "flag");
			return (Criteria) this;
		}

		public Criteria andFlagNotIn(List<Byte> values) {
			addCriterion("flag not in", values, "flag");
			return (Criteria) this;
		}

		public Criteria andFlagBetween(Byte value1, Byte value2) {
			addCriterion("flag between", value1, value2, "flag");
			return (Criteria) this;
		}

		public Criteria andFlagNotBetween(Byte value1, Byte value2) {
			addCriterion("flag not between", value1, value2, "flag");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table sale_record
	 * @mbg.generated  Mon Dec 10 23:32:09 CST 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	private Integer limit;

    private Integer offset;

    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    public Integer getLimit() {
        return limit;
    }

    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    public Integer getOffset() {
        return offset;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sale_record
     *
     * @mbg.generated do_not_delete_during_merge Mon Dec 10 16:39:48 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}