package com.yh.tradease.sales.entity;

import java.util.Date;
import java.util.List;

import org.springframework.format.annotation.DateTimeFormat;

public class WholesaleRecord {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wholesale_record.id
	 * @mbg.generated  Mon Dec 17 00:39:32 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wholesale_record.name
	 * @mbg.generated  Mon Dec 17 00:39:32 CST 2018
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wholesale_record.order_time
	 * @mbg.generated  Mon Dec 17 00:39:32 CST 2018
	 */
	@DateTimeFormat(pattern = "yyyy-MM-dd HH:ss:mm")
	private Date orderTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wholesale_record.delivery_time
	 * @mbg.generated  Mon Dec 17 00:39:32 CST 2018
	 */
	@DateTimeFormat(pattern = "yyyy-MM-dd HH:ss:mm")
	private Date deliveryTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wholesale_record.buyer
	 * @mbg.generated  Mon Dec 17 00:39:32 CST 2018
	 */
	private Integer buyer;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wholesale_record.phone
	 * @mbg.generated  Mon Dec 17 00:39:32 CST 2018
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wholesale_record.address
	 * @mbg.generated  Mon Dec 17 00:39:32 CST 2018
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wholesale_record.payed
	 * @mbg.generated  Mon Dec 17 00:39:32 CST 2018
	 */
	private Double payed;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wholesale_record.unpayed
	 * @mbg.generated  Mon Dec 17 00:39:32 CST 2018
	 */
	private Double unpayed;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wholesale_record.total_price
	 * @mbg.generated  Mon Dec 17 00:39:32 CST 2018
	 */
	private Double totalPrice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wholesale_record.discount
	 * @mbg.generated  Mon Dec 17 00:39:32 CST 2018
	 */
	private Double discount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wholesale_record.real_price
	 * @mbg.generated  Mon Dec 17 00:39:32 CST 2018
	 */
	private Double realPrice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wholesale_record.delivery_type
	 * @mbg.generated  Mon Dec 17 00:39:32 CST 2018
	 */
	private Byte deliveryType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wholesale_record.order_status
	 * @mbg.generated  Mon Dec 17 00:39:32 CST 2018
	 */
	private Byte orderStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wholesale_record.delivery_status
	 * @mbg.generated  Mon Dec 17 00:39:32 CST 2018
	 */
	private Byte deliveryStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wholesale_record.remark
	 * @mbg.generated  Mon Dec 17 00:39:32 CST 2018
	 */
	private String remark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wholesale_record.cdate
	 * @mbg.generated  Mon Dec 17 00:39:32 CST 2018
	 */
	
	private List<OrderDetail> orderDetails;
	@DateTimeFormat(pattern = "yyyy-MM-dd HH:ss:mm")
	private Date cdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wholesale_record.mdate
	 * @mbg.generated  Mon Dec 17 00:39:32 CST 2018
	 */
	@DateTimeFormat(pattern = "yyyy-MM-dd HH:ss:mm")
	private Date mdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wholesale_record.flag
	 * @mbg.generated  Mon Dec 17 00:39:32 CST 2018
	 */
	private Byte flag;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wholesale_record.id
	 * @return  the value of wholesale_record.id
	 * @mbg.generated  Mon Dec 17 00:39:32 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wholesale_record.id
	 * @param id  the value for wholesale_record.id
	 * @mbg.generated  Mon Dec 17 00:39:32 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wholesale_record.name
	 * @return  the value of wholesale_record.name
	 * @mbg.generated  Mon Dec 17 00:39:32 CST 2018
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wholesale_record.name
	 * @param name  the value for wholesale_record.name
	 * @mbg.generated  Mon Dec 17 00:39:32 CST 2018
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wholesale_record.order_time
	 * @return  the value of wholesale_record.order_time
	 * @mbg.generated  Mon Dec 17 00:39:32 CST 2018
	 */
	public Date getOrderTime() {
		return orderTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wholesale_record.order_time
	 * @param orderTime  the value for wholesale_record.order_time
	 * @mbg.generated  Mon Dec 17 00:39:32 CST 2018
	 */
	public void setOrderTime(Date orderTime) {
		this.orderTime = orderTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wholesale_record.delivery_time
	 * @return  the value of wholesale_record.delivery_time
	 * @mbg.generated  Mon Dec 17 00:39:32 CST 2018
	 */
	public Date getDeliveryTime() {
		return deliveryTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wholesale_record.delivery_time
	 * @param deliveryTime  the value for wholesale_record.delivery_time
	 * @mbg.generated  Mon Dec 17 00:39:32 CST 2018
	 */
	public void setDeliveryTime(Date deliveryTime) {
		this.deliveryTime = deliveryTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wholesale_record.buyer
	 * @return  the value of wholesale_record.buyer
	 * @mbg.generated  Mon Dec 17 00:39:32 CST 2018
	 */
	public Integer getBuyer() {
		return buyer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wholesale_record.buyer
	 * @param buyer  the value for wholesale_record.buyer
	 * @mbg.generated  Mon Dec 17 00:39:32 CST 2018
	 */
	public void setBuyer(Integer buyer) {
		this.buyer = buyer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wholesale_record.phone
	 * @return  the value of wholesale_record.phone
	 * @mbg.generated  Mon Dec 17 00:39:32 CST 2018
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wholesale_record.phone
	 * @param phone  the value for wholesale_record.phone
	 * @mbg.generated  Mon Dec 17 00:39:32 CST 2018
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wholesale_record.address
	 * @return  the value of wholesale_record.address
	 * @mbg.generated  Mon Dec 17 00:39:32 CST 2018
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wholesale_record.address
	 * @param address  the value for wholesale_record.address
	 * @mbg.generated  Mon Dec 17 00:39:32 CST 2018
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wholesale_record.payed
	 * @return  the value of wholesale_record.payed
	 * @mbg.generated  Mon Dec 17 00:39:32 CST 2018
	 */
	public Double getPayed() {
		return payed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wholesale_record.payed
	 * @param payed  the value for wholesale_record.payed
	 * @mbg.generated  Mon Dec 17 00:39:32 CST 2018
	 */
	public void setPayed(Double payed) {
		this.payed = payed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wholesale_record.unpayed
	 * @return  the value of wholesale_record.unpayed
	 * @mbg.generated  Mon Dec 17 00:39:32 CST 2018
	 */
	public Double getUnpayed() {
		return unpayed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wholesale_record.unpayed
	 * @param unpayed  the value for wholesale_record.unpayed
	 * @mbg.generated  Mon Dec 17 00:39:32 CST 2018
	 */
	public void setUnpayed(Double unpayed) {
		this.unpayed = unpayed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wholesale_record.total_price
	 * @return  the value of wholesale_record.total_price
	 * @mbg.generated  Mon Dec 17 00:39:32 CST 2018
	 */
	public Double getTotalPrice() {
		return totalPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wholesale_record.total_price
	 * @param totalPrice  the value for wholesale_record.total_price
	 * @mbg.generated  Mon Dec 17 00:39:32 CST 2018
	 */
	public void setTotalPrice(Double totalPrice) {
		this.totalPrice = totalPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wholesale_record.discount
	 * @return  the value of wholesale_record.discount
	 * @mbg.generated  Mon Dec 17 00:39:32 CST 2018
	 */
	public Double getDiscount() {
		return discount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wholesale_record.discount
	 * @param discount  the value for wholesale_record.discount
	 * @mbg.generated  Mon Dec 17 00:39:32 CST 2018
	 */
	public void setDiscount(Double discount) {
		this.discount = discount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wholesale_record.real_price
	 * @return  the value of wholesale_record.real_price
	 * @mbg.generated  Mon Dec 17 00:39:32 CST 2018
	 */
	public Double getRealPrice() {
		return realPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wholesale_record.real_price
	 * @param realPrice  the value for wholesale_record.real_price
	 * @mbg.generated  Mon Dec 17 00:39:32 CST 2018
	 */
	public void setRealPrice(Double realPrice) {
		this.realPrice = realPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wholesale_record.delivery_type
	 * @return  the value of wholesale_record.delivery_type
	 * @mbg.generated  Mon Dec 17 00:39:32 CST 2018
	 */
	public Byte getDeliveryType() {
		return deliveryType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wholesale_record.delivery_type
	 * @param deliveryType  the value for wholesale_record.delivery_type
	 * @mbg.generated  Mon Dec 17 00:39:32 CST 2018
	 */
	public void setDeliveryType(Byte deliveryType) {
		this.deliveryType = deliveryType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wholesale_record.order_status
	 * @return  the value of wholesale_record.order_status
	 * @mbg.generated  Mon Dec 17 00:39:32 CST 2018
	 */
	public Byte getOrderStatus() {
		return orderStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wholesale_record.order_status
	 * @param orderStatus  the value for wholesale_record.order_status
	 * @mbg.generated  Mon Dec 17 00:39:32 CST 2018
	 */
	public void setOrderStatus(Byte orderStatus) {
		this.orderStatus = orderStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wholesale_record.delivery_status
	 * @return  the value of wholesale_record.delivery_status
	 * @mbg.generated  Mon Dec 17 00:39:32 CST 2018
	 */
	public Byte getDeliveryStatus() {
		return deliveryStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wholesale_record.delivery_status
	 * @param deliveryStatus  the value for wholesale_record.delivery_status
	 * @mbg.generated  Mon Dec 17 00:39:32 CST 2018
	 */
	public void setDeliveryStatus(Byte deliveryStatus) {
		this.deliveryStatus = deliveryStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wholesale_record.remark
	 * @return  the value of wholesale_record.remark
	 * @mbg.generated  Mon Dec 17 00:39:32 CST 2018
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wholesale_record.remark
	 * @param remark  the value for wholesale_record.remark
	 * @mbg.generated  Mon Dec 17 00:39:32 CST 2018
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wholesale_record.cdate
	 * @return  the value of wholesale_record.cdate
	 * @mbg.generated  Mon Dec 17 00:39:32 CST 2018
	 */
	public Date getCdate() {
		return cdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wholesale_record.cdate
	 * @param cdate  the value for wholesale_record.cdate
	 * @mbg.generated  Mon Dec 17 00:39:32 CST 2018
	 */
	public void setCdate(Date cdate) {
		this.cdate = cdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wholesale_record.mdate
	 * @return  the value of wholesale_record.mdate
	 * @mbg.generated  Mon Dec 17 00:39:32 CST 2018
	 */
	public Date getMdate() {
		return mdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wholesale_record.mdate
	 * @param mdate  the value for wholesale_record.mdate
	 * @mbg.generated  Mon Dec 17 00:39:32 CST 2018
	 */
	public void setMdate(Date mdate) {
		this.mdate = mdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wholesale_record.flag
	 * @return  the value of wholesale_record.flag
	 * @mbg.generated  Mon Dec 17 00:39:32 CST 2018
	 */
	public Byte getFlag() {
		return flag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wholesale_record.flag
	 * @param flag  the value for wholesale_record.flag
	 * @mbg.generated  Mon Dec 17 00:39:32 CST 2018
	 */
	public void setFlag(Byte flag) {
		this.flag = flag;
	}

	public List<OrderDetail> getOrderDetails() {
		return orderDetails;
	}

	public void setOrderDetails(List<OrderDetail> orderDetails) {
		this.orderDetails = orderDetails;
	}
	
}