package com.yh.tradease.serve.dao;

import com.yh.tradease.serve.entity.ProductInstall;
import com.yh.tradease.serve.entity.ProductInstallExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ProductInstallMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_install
	 * @mbg.generated  Mon Dec 17 01:45:08 CST 2018
	 */
	long countByExample(ProductInstallExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_install
	 * @mbg.generated  Mon Dec 17 01:45:08 CST 2018
	 */
	int deleteByExample(ProductInstallExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_install
	 * @mbg.generated  Mon Dec 17 01:45:08 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_install
	 * @mbg.generated  Mon Dec 17 01:45:08 CST 2018
	 */
	int insert(ProductInstall record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_install
	 * @mbg.generated  Mon Dec 17 01:45:08 CST 2018
	 */
	int insertSelective(ProductInstall record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_install
	 * @mbg.generated  Mon Dec 17 01:45:08 CST 2018
	 */
	List<ProductInstall> selectByExample(ProductInstallExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_install
	 * @mbg.generated  Mon Dec 17 01:45:08 CST 2018
	 */
	ProductInstall selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_install
	 * @mbg.generated  Mon Dec 17 01:45:08 CST 2018
	 */
	int updateByExampleSelective(@Param("record") ProductInstall record,
			@Param("example") ProductInstallExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_install
	 * @mbg.generated  Mon Dec 17 01:45:08 CST 2018
	 */
	int updateByExample(@Param("record") ProductInstall record, @Param("example") ProductInstallExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_install
	 * @mbg.generated  Mon Dec 17 01:45:08 CST 2018
	 */
	int updateByPrimaryKeySelective(ProductInstall record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_install
	 * @mbg.generated  Mon Dec 17 01:45:08 CST 2018
	 */
	int updateByPrimaryKey(ProductInstall record);
}