package com.yh.tradease.serve.dao;

import com.yh.tradease.serve.entity.ProductRepair;
import com.yh.tradease.serve.entity.ProductRepairExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface ProductRepairMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_repair
     *
     * @mbg.generated Tue Dec 18 01:18:05 CST 2018
     */
    long countByExample(ProductRepairExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_repair
     *
     * @mbg.generated Tue Dec 18 01:18:05 CST 2018
     */
    int deleteByExample(ProductRepairExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_repair
     *
     * @mbg.generated Tue Dec 18 01:18:05 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_repair
     *
     * @mbg.generated Tue Dec 18 01:18:05 CST 2018
     */
    int insert(ProductRepair record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_repair
     *
     * @mbg.generated Tue Dec 18 01:18:05 CST 2018
     */
    int insertSelective(ProductRepair record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_repair
     *
     * @mbg.generated Tue Dec 18 01:18:05 CST 2018
     */
    List<ProductRepair> selectByExample(ProductRepairExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_repair
     *
     * @mbg.generated Tue Dec 18 01:18:05 CST 2018
     */
    ProductRepair selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_repair
     *
     * @mbg.generated Tue Dec 18 01:18:05 CST 2018
     */
    int updateByExampleSelective(@Param("record") ProductRepair record, @Param("example") ProductRepairExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_repair
     *
     * @mbg.generated Tue Dec 18 01:18:05 CST 2018
     */
    int updateByExample(@Param("record") ProductRepair record, @Param("example") ProductRepairExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_repair
     *
     * @mbg.generated Tue Dec 18 01:18:05 CST 2018
     */
    int updateByPrimaryKeySelective(ProductRepair record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_repair
     *
     * @mbg.generated Tue Dec 18 01:18:05 CST 2018
     */
    int updateByPrimaryKey(ProductRepair record);
}