package com.yh.tradease.product.dao;

import com.yh.tradease.product.entity.ProductModule;
import com.yh.tradease.product.entity.ProductModuleExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface ProductModuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_module
     *
     * @mbg.generated Mon Dec 24 00:38:05 CST 2018
     */
    long countByExample(ProductModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_module
     *
     * @mbg.generated Mon Dec 24 00:38:05 CST 2018
     */
    int deleteByExample(ProductModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_module
     *
     * @mbg.generated Mon Dec 24 00:38:05 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_module
     *
     * @mbg.generated Mon Dec 24 00:38:05 CST 2018
     */
    int insert(ProductModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_module
     *
     * @mbg.generated Mon Dec 24 00:38:05 CST 2018
     */
    int insertSelective(ProductModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_module
     *
     * @mbg.generated Mon Dec 24 00:38:05 CST 2018
     */
    List<ProductModule> selectByExample(ProductModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_module
     *
     * @mbg.generated Mon Dec 24 00:38:05 CST 2018
     */
    ProductModule selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_module
     *
     * @mbg.generated Mon Dec 24 00:38:05 CST 2018
     */
    int updateByExampleSelective(@Param("record") ProductModule record, @Param("example") ProductModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_module
     *
     * @mbg.generated Mon Dec 24 00:38:05 CST 2018
     */
    int updateByExample(@Param("record") ProductModule record, @Param("example") ProductModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_module
     *
     * @mbg.generated Mon Dec 24 00:38:05 CST 2018
     */
    int updateByPrimaryKeySelective(ProductModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_module
     *
     * @mbg.generated Mon Dec 24 00:38:05 CST 2018
     */
    int updateByPrimaryKey(ProductModule record);
    /**
     * 
     * @Title: getTree   
     * @Description: 查询产品模块树
     * @param: @param i
     * @param: @return      
     * @return: List<ProductModule>      
     * @throws
     */
    List<ProductModule> getTree(int i);
}